codex-storage/nim-codex

dagger/blockexchange/engine.nim, nim.cfg, tests/dagger/testblockexc.nim, tests/dagger/testblockset.nim, tests/dagger/teststores.nim
Fixes unused imports.
Disables `LockLevel` and `ObservableStores` warnings because they are
not relevant for our codebase and obfuscate other warnings that are relevant.
=> Fix warnings

tests/dagger/blockexc/testnetwork.nim
The 100 millisecond timeouts in the tests were a bit too short, bumped to 500 milliseconds.
=> Fix occasional test failure due to timeout

env.sh
`env.sh` is copied verbatim from: https://github.com/status-im/nimbus-build-system#envsh
---
This is simply for convenience; see e.g. https://github.com/status-im/nim-dagger/pull/33#issuecomment-996076749.
=> add env.sh shim to project root

.github/workflows/ci.yml
- removes i386 architecture
- removes running with nim 1.4.x
- no longer run twice for PRs (both on push and on PR)
=> Speed up CI by eliminating unnecessary runs

dagger/conf.nim
Split off from #84, to allow https://github.com/status-im/infra-role-nim-codex/pull/2 to move forward without needing to wait on it to be finished completely.
=> Add --eth-provider and --eth-account options

dagger/conf.nim, dagger/contracts/deployment.nim, dagger/contracts/interactions.nim, dagger/dagger.nim, dagger/node.nim, tests/contracts/testInteractions.nim, tests/dagger/testnode.nim
Adds --eth-deployment parameter to specify where the deployment json file is located.
Ensures that the node does not crash when deployment json is missing or incorrect.
=> [contracts] Make contract interactions optional in the node

config.nims
These patches enable arm64+Neon builds of Codex
Build and tests pass on:
- Apple M1 under MacOS (Big Sur 11.6.1)
- Apple M1 under Ubuntu (20.04.2 ARM64 in a Parallels VM)
- Rock64 SBC with RK3328 (DietPi)
- Raspberry Pi 3 B+ with Broadcom BCM2837 (64-bit RasberryOS)
Changes
- Implement and merge arm64 in Leopard (https://github.com/status-im/leopard/pull/1)
- fix -march in config.nims
Signed-off-by: Csaba Kiraly <csaba.kiraly@gmail.com>
=> enable build on Mac M1 and other arm64+Neon architectures

Makefile
Otherwise `-G"MinGW Makefiles"` is [included in `CMAKE_ARGS`](https://github.com/status-im/nim-libbacktrace/blob/284b3aac05a9d96c27044c389a5d27a84d8e8f4b/Makefile#L105), which does not function correctly in MSYS2 Bash.
=> build: override CMAKE_ARGS for Windows+MSYS2 environments re: libbacktrace

.gitmodules, codex/codex.nim, codex/node.nim, codex/stores.nim, codex/stores/blockstore.nim, codex/stores/cachestore.nim, codex/stores/fsstore.nim, codex/stores/networkstore.nim, codex/stores/sqlitestore.nim, tests/codex/storageproofs/testnetwork.nim, tests/codex/storageproofs/teststpstore.nim, tests/codex/stores/testcachestore.nim, tests/codex/stores/testfsstore.nim, tests/codex/stores/testsqlitestore.nim, tests/codex/teststores.nim
This PR adds an implementation of `SQLiteStore` that can function as a drop-in replacement for `FSStore`, and I've made that replacement in `codex/codex.nim`.
During the process I looked for opportunities to integrate nim-datastore more directly, i.e. as opposed to wrapping `type SQliteDatastore` inside of this PR's `type SQLiteStore`. That should be possible, but will be a more significant set of changes and there should be additional discussion. I think a good context to consider such changes is #137.
Also, the drop-in approach will allow for a more direct performance comparison per #131.
Closes #138.
=> add SQLiteStore backend

codex/contracts/market.nim, codex/contracts/requests.nim, codex/contracts/storage.nim, codex/market.nim, codex/node.nim, codex/purchasing.nim, codex/rest/api.nim, codex/rest/json.nim, codex/sales.nim, tests/codex/helpers/mockmarket.nim, tests/codex/testpurchasing.nim, tests/codex/testsales.nim, tests/contracts/examples.nim, tests/contracts/testContracts.nim, tests/contracts/testMarket.nim, tests/testIntegration.nim
Allows multiple slots in a storage contract, so that more than one host can contribute.
A step towards the design in https://github.com/status-im/codex-research/pull/83.
Uses the smart contract update from https://github.com/status-im/dagger-contracts/pull/13.
=> Multiple slots in a storage contract

codex/codex.nim, codex/stores/sqlitestore.nim, tests/codex/stores/testsqlitestore.nim
Also fix a discrepancy where cli option `--cache-size` is documented as `0 disables the cache` in `codex/conf.nim`, but previously the value `0` would result in a cache being constructed with default parameter values for `CacheStore.new()`
Closes #180.
=> support self.cache=nil in SQLiteStore

codex/codex.nim, codex/conf.nim, codex/contracts/interactions.nim, codex/node.nim, tests/codex/testnode.nim, tests/contracts/testInteractions.nim, tests/testIntegration.nim
All interactions with the Ethereum node are disabled by default. Only when the ~~`--enable-eth`~~ `--persistence` parameter is set, do we start interactions with the Ethereum node.
Includes improved error messages when parameters are missing, or the Ethereum node is not reachable.
fixes #163
=> Better command line options for Ethereum

codex/erasure/erasure.nim
ECC decoding can be done with any encoded.K blocks, and now we start it once any K blocks arrived.
Previous code essentially waited for all blocks to arrive (or fail to arrive), that may mean unnecessary delays.
New code will sometimes ECC-decode when parity blocks were retrieved faster that data blocks (instead of waiting for data blocks from network), but we expect that it's OK due to extremely fast Leopard decoding (~~500 MB/s)
=> Quickfix: start erasure decoding once any K blocks arrived

codex/blockexchange/engine/engine.nim, codex/blocktype.nim, codex/erasure/erasure.nim, codex/node.nim, codex/stores/blockstore.nim, codex/stores/cachestore.nim, codex/stores/fsstore.nim, codex/stores/networkstore.nim, codex/stores/sqlitestore.nim, codex/streams/storestream.nim, tests/codex/blockexchange/engine/testblockexc.nim, tests/codex/helpers.nim, tests/codex/stores/testcachestore.nim, tests/codex/stores/testfsstore.nim, tests/codex/stores/testsqlitestore.nim, tests/codex/testnode.nim
Change return type for `method getBlock` from `Future[?!(?Block)]` to `Future[?!Block]`.
Use `type BlockNotFoundError = object of CodexError` to differentiate between *"block not found in the store"* and other errors.
Also make some logic and error handling/messages more consistent across `BlockStore` implementations.
Closes #177.
Closes #182.
Closes #210.
Alternative to #205, #209.
---
What I was missing previously was understanding of how at runtime to use Nim's [`of` operator](https://nim-lang.org/docs/manual.html#types-tuples-and-object-types) to distinguish error types inheriting from `CatchableError`
> Objects provide many features that tuples do not. Objects provide inheritance and the ability to hide fields from other modules. Objects with inheritance enabled have information …
=> update getBlock return type

codex/chunker.nim, codex/manifest/coders.nim, codex/manifest/manifest.nim, codex/manifest/types.nim, codex/node.nim, codex/streams/storestream.nim, codex/utils.nim, tests/codex/helpers/randomchunker.nim, tests/codex/testchunking.nim, tests/codex/testnode.nim
Note that the wire format of Manifest was changed, so we need to recreate all BlockStores.
Closes #98.
=> Download files without padding

codex/contracts/market.nim, codex/contracts/proofs.nim, codex/contracts/requests.nim, codex/contracts/storage.nim, codex/market.nim, codex/node.nim, codex/proving.nim, codex/purchasing.nim, codex/rest/api.nim, codex/rest/json.nim, codex/sales.nim, codex/storageproofs/timing/proofs.nim, tests/codex/helpers/mockmarket.nim, tests/codex/helpers/mockproofs.nim, tests/codex/testproving.nim, tests/contracts/examples.nim, tests/contracts/testContracts.nim, tests/contracts/testMarket.nim, tests/contracts/testProofs.nim, tests/examples.nim
Cleaning up the variety of `array[32, byte]`'s to make the code a bit more descriptive and avoid confusion between types like `RequestId` and `SlotId`.
- rename `ContractId` to `SlotId`
- add `RequestId`, `PurchaseId`, `Nonce` types as distinct aliases of `array[32, byte]`
- rename `Proving.contracts` to `Proving.slots`
- Add/modify conversions to support the distinct type (ABI encoding/decoding, JSON encoding, REST decoding).
- Update tests 
Closes #214
Closes #184 (duplicate)
Updates nim-ethers dependency to PR branch https://github.com/status-im/nim-ethers/pull/31. Probably best to merge the nim-ethers PR first, then update the commit hash to point to main.
=> [chore] clean up `array[32, byte]` types

Makefile
With this change `make exec` runs a release build instead of a debug build.
=> pass NIM_PARAMS to nim compiler in exec target of Makefile

.gitmodules
PR #236 introduced a mistake, adding `vendor/vendor/nim-eth` to `.gitmodules`.
This PR corrects that mistakes and bumps `vendor/nim-eth` to the latest commit on upstream's `master`. With that change it's also necessary to bump `vendor/nim-bearssl`. Also drop `vendor/bearssl` as it's not needed.
=> Fix vendor/nim-eth

codex/blockexchange/protobuf/message.proto
We incorrectly assigned code 2 to the payload field instead of code 3:
Our code: https://github.com/status-im/nim-codex/blob/8c5939252607f74b60a49fee4570734ffa06b11c/codex/blockexchange/protobuf/message.proto#L50-L52
While original code: https://github.com/ipfs/go-bitswap/blob/0fa397581ca6197c6c4ca17842719370f6596e95/message/pb/message.proto#L43-L45
And [documentation](https://github.com/ipfs/specs/blob/main/BITSWAP.md#bitswap-120-wire-format).
=> Fixed message.proto to match IPFS specs

codex/discovery.nim
Uses dht with providers lru, should be updated once https://github.com/status-im/nim-libp2p-dht/pull/44 is merged.
=> Dht providers lru

codex/contracts/clock.nim
Use a sub-second offset to avoid off-by-one errors in the test at the second boundary.
Co-authored-by: @emizzle
=> [contracts] Fix intermittently failing clock test

codex/purchasing.nim, codex/purchasing/purchase.nim, codex/purchasing/purchaseid.nim, codex/purchasing/statemachine.nim, codex/purchasing/states/cancelled.nim, codex/purchasing/states/error.nim, codex/purchasing/states/pending.nim, codex/purchasing/states/started.nim, codex/purchasing/states/submitted.nim, codex/utils/optionalcast.nim, codex/utils/statemachine.nim, tests/codex/testutils.nim, tests/codex/utils/testoptionalcast.nim, tests/codex/utils/teststatemachine.nim, tests/testCodex.nim
A Purchase already underwent several stages before it was completed. This refactor makes the states that a purchase goes through explicit using a state pattern.
This is part of the work to ensure that purchases survive a restart of the node.
=> Rework Purchase as a state machine

codex.nim, codex/codex.nim, codex/conf.nim, codex/discovery.nim, codex/rest/api.nim, codex/utils/addrutils.nim, codex/utils/keyutils.nim, tests/codex/helpers/nodeutils.nim, tests/codex/storageproofs/testnetwork.nim, tests/codex/testnode.nim, tests/testIntegration.nim
This PR adds support for persisting the private key. 
In addition it attempts to add more complete support for advertising and listening addresses. 
It adds the following options:
- `listen-addrs` - multiaddresses that the node listens on as well as announces as providers over the DHT. Making them multiaddresses allows listening on different transports, such as tcp and websockets, etc... 
- After node startup, provider addresses are remapped with the IP set with `--nat`, this is done so that addresses are properly announced in case of `0.0.0.0`
- `nat` - allows specifying an external address and used when creating the bootstrap spr. (It should be extended to support more NAT related options, such as upnp, pmp, extip, etc...)
- `discoveryIp` and `discoveryPort` - bind ip and port for the …
=> setup and persist private key

codex.nim, codex/blockexchange/engine/discovery.nim, codex/blockexchange/engine/engine.nim, codex/blockexchange/engine/pendingblocks.nim, codex/blockexchange/network/network.nim, codex/blockexchange/network/networkpeer.nim, codex/blockexchange/peers/peercontext.nim, codex/blockexchange/peers/peerctxstore.nim, codex/blockexchange/protobuf/message.nim, codex/blockexchange/protobuf/presence.nim, codex/chunker.nim, codex/codex.nim, codex/conf.nim, codex/erasure/erasure.nim, codex/node.nim, codex/stores/cachestore.nim, codex/stores/fsstore.nim, codex/streams/storestream.nim, tests/codex/blockexchange/discovery/testdiscovery.nim, tests/codex/blockexchange/discovery/testdiscoveryengine.nim, tests/codex/blockexchange/engine/testblockexc.nim, tests/codex/blockexchange/engine/testengine.nim, tests/codex/blockexchange/protobuf/testpresence.nim, tests/codex/blockexchange/testnetwork.nim, tests/codex/blockexchange/testpeerctxstore.nim
The current implementation has several flaws that lead to download performance degradation with more than one peer. This PR attempts to address some of this issues.
- Current transfer is around ~10MB/s, this can be further improved with parallel downloads and similar
=> Block download

config.nims
Ensures that we include the correct paths when building with nimbus-build-system.
Fixes Error: cannot open file: ""
Copied from:
https://github.com/status-im/nimbus-eth2/blob/1ea102b033b13847298fef4a79c802186ffcf538/config.nims#L5
=> [build] fix nimbus-build-system

codex/sales.nim, codex/sales/salesagent.nim, codex/sales/salescontext.nim, codex/sales/statemachine.nim, codex/sales/states/cancelled.nim, codex/sales/states/downloading.nim, codex/sales/states/errored.nim, codex/sales/states/errorhandling.nim, codex/sales/states/failed.nim, codex/sales/states/filled.nim, codex/sales/states/filling.nim, codex/sales/states/finished.nim, codex/sales/states/proving.nim, codex/sales/states/unknown.nim, codex/utils/asyncstatemachine.nim, tests/codex/helpers/mockmarket.nim, tests/codex/sales/testsales.nim, tests/codex/utils/testasyncstatemachine.nim
- add error handling to catch errors during `state.run`
- Sales: create `ErrorHandlingState` to use a base class for handling the `onError` callback, which is called when there is an error in the state's run method.
- Sales: `onError` can be overridden by individual states if needed.
- Because there is already a state named SaleFailed which is meant to react to an onchain `RequestFailed` event and also because this callback is called from `SaleErrored`, renaming to `onSaleErrored` prevents ambiguity and confusion as to what has happened at the callback callsite.
- base branch is #306
=> [sales statemachine] add async state machine error handling

codex/sales/salesagent.nim, codex/utils/asyncstatemachine.nim, tests/codex/sales/testsalesagent.nim
1. prevent memory leaks and nil access defects by:
- allowing multiple subscribe/unsubscribes of salesagent
- disallowing individual salesagent subscription calls to be made externally (requires the .subscribed check)
- allowing mutiple start/stops of asyncstatemachine
- disregard asyncstatemachine schedules if machine not yet started
2. add salesagent tests:
- test multiple subscribe/unsubscribes
- test scheduling machine without being started
- test subscriptions are working correctly with external events
- test errors can be overridden at the state level for ErrorHandlingStates.
=> [sales statemachine] prevent memory leaks and add salesagent tests

README.md, codex/codex.nim, codex/conf.nim
Slight diffs from that PR:
A) renaming to --repo-kind which makes more sense in the current code
and B) without a working cacheStore (yet)
Tagging related https://github.com/status-im/nim-codex/issues/357
=> Resuscitate https://github.com/status-im/nim-codex/pull/251

tests/config.nims, tests/logging.nim, tests/nim.cfg, tests/testCodex.nim, tests/testContracts.nim, tests/testIntegration.nim
Ensures that logging is ignored at runtime when running individual tests using `nim c -r tests/...`
=> [build] fix: ignore logging when running singular tests

.github/workflows/docs.yml
This PR enables the linting of OpenAPI on all PRs, while keeping the deployment only for the `main` branches
=> ci: lint openapi on all prs

BUILDING.md, README.md
In #356 `make exec` was replaced with the default `make` call, but the docs still refer to `make exec`.
=> Update references to `make exec`

openapi.yaml
Documentation in the REST OpenAPI spec were showing incorrect information about Purchasing endpoints.
Update the open api spec to reflect information about purchases, not requests.
=> [rest api] fix purchases documentation

README.md, codex/contracts/market.nim, codex/proving.nim, codex/sales/salesagent.nim, codex/sales/states/downloading.nim, codex/sales/states/errored.nim, codex/sales/states/filling.nim, codex/sales/states/finished.nim, codex/sales/states/proving.nim, tests/integration/nodes.nim, tests/integration/testIntegration.nim, tests/integration/twonodes.nim
This PR adds hotfix-style support for collecting a host's reward. It is plugged into the proving component, but it will be refactored later, as described in #414. 
The test case is also temporary, as we currently do not have any endpoint that would expose the state of a host's requests that he or she hosts. This will be improved once #415 is fixed. 
As I had a hard time making the test pass, I have improved the logging support for the Sales State Machine, integration tests, and some documentation around this. Only then I have realized that the proving component requires new blocks to be mined in order for the proving cycle to kick in, so I added `provider.advanceTime()` and then all worked 🙄
=> feat: storage host collects reward

.github/workflows/Readme.md, BUILDING.md, README.md
Some badges may not show status correctly and as we moved repository it is better to update all the links to point to the new organization.
=> Update links to codex-storage organization

.github/workflows/docs.yml
We recently renamed `main` branch into the `master` and it broke the [Open API workflow](../../actions/workflows/docs.yml).
codex-storage/infra-codex/issues/5
=> Fix Open API workflow branch

codex.nimble, codex/codex.nim, codex/conf.nim
- Fix weird nimsuggest failures with static getCodexVersion and rng.Rng. Now nimsuggest doesn't routinely crash. 
- Some formatting tweaks. It's a style I've seen "in the wild" in a few Nim projects and find that for procs with many variables it helps readability. In particular the return type is much quicker to pick out which helps with `Result` types.
=> Nimsuggest tweaks

codex.nim, codex/blocktype.nim, codex/chunker.nim, codex/codex.nim, codex/conf.nim, codex/erasure/erasure.nim, codex/manifest/coders.nim, codex/manifest/manifest.nim, codex/manifest/types.nim, codex/node.nim, codex/rest/api.nim, codex/stores/cachestore.nim, codex/streams/storestream.nim, codex/units.nim, codex/utils.nim, tests/codex/blockexchange/engine/testblockexc.nim, tests/codex/blockexchange/engine/testengine.nim, tests/codex/helpers.nim, tests/codex/helpers/randomchunker.nim, tests/codex/storageproofs/testnetwork.nim, tests/codex/storageproofs/testpor.nim, tests/codex/storageproofs/teststpstore.nim, tests/codex/stores/testcachestore.nim, tests/codex/testchunking.nim, tests/codex/testerasure.nim, tests/codex/testnode.nim, tests/codex/teststorestream.nim
Plumbs in `type NBytes* = Natural` to represent a number of bytes. This is used in to both document the code where units are in bytes. It also provides the ability to add bytes units for confutils (see https://github.com/codex-storage/nim-codex/issues/466). 
With this PR this now works: `./build/codex --storage-quota=5MB`. Units are always in 1024 powers (not base 10). 
I settled changing Manifest and CacheStore to use `NBytes` while not using it in the more low level stream objects. It mostly adds value at that layer which more describes the system behavior. 
Also, I tried out a couple of naming variants, but found `Bytes` too confusing and `ByteSize` or `SizeBytes` less aesthetics.
=> Plumbing in conf types

codex/clock.nim, codex/contracts/clock.nim, tests/contracts/testClock.nim, tests/integration/testproofs.nim
`OnChainClock.waitUntil()` should now finish immediately when a new block arrives that has a timestamp after the due date. Previously it could take up to one second to complete the future. This messed with the timings in the
integration tests and made them less predictable. As an added benefit, we can now tighten the sleeps in the integration test so they finish faster.
=> Speed up clock.waitUntil()

.github/workflows/ci.yml
Splite the unit, contract, and integration tests into separate parts. 
This incurs a slight overhead per Windows VM for duplicating `nimble setup` stages (~3min) but should cut each windows run down to ~20-25min. 
Another possible issue would be CI time. IIRC, Github Actions charge per minute. If so that'd mean the total minutes of CI runner time would roughly be about the same (give or take 3x * 3min or so).
If anyone else knows of other downsides let me know!
=> split windows CI tests into parts

codex/purchasing/purchase.nim, codex/sales.nim, codex/sales/salesagent.nim, codex/sales/slotqueue.nim, codex/utils/asyncstatemachine.nim, codex/utils/then.nim, codex/utils/trackedfutures.nim, tests/codex/sales/testsalesagent.nim, tests/codex/testutils.nim, tests/codex/utils/testasyncstatemachine.nim, tests/codex/utils/testthen.nim, tests/codex/utils/testtrackedfutures.nim
Fixes #490.
Previously, the async state machine created futures for the current state's run method, the internal state machine's scheduler, and the `AsyncQueue.pop` that waits for events to be pushed to the queue. During `stop`, all three of these futures are now cancelled and waited before completing `stop`.
The implementation uses the `TrackedFutures` to track both futures, and `machine.trackedFutures.cancelTracked` in `stop`.
Simplifications to the `then` (promise) api were made that removed multiple callbacks in `.then`, borrowed from the javascript promise api. Additionally, the `then` tests were revamped for simplicity.
The `TrackedFutures` module was updated to remove tracked futures when a future is cancelled, and all futures are removed from the table once `cancelTracked` …
=> Cancel and wait for asyncstatemachine futures when stopping

codex/sales.nim, tests/codex/sales/testsales.nim
=> fix: load slots on sales module start

.github/workflows/docker-dist-tests.yml, .github/workflows/docker-reusable.yml
This PR adds reusable workflow for Docker builds (codex-storage/cs-codex-dist-tests/issues/42)
1. Reusable workflow - `docker-reusable.yml`
2. Main workflow - `docker.yml`
3. Dist-Tests workflow - `docker-dist-tests.yml`
```yaml
jobs:
build-and-push:
name: Build and Push
uses: ./.github/workflows/docker-reusable.yaml
secrets: inherit
jobs:
build-and-push:
name: Build and Push
uses: ./.github/workflows/docker-reusable.yaml
with:
docker_file: docker/codex.Dockerfile
docker_repo: codexstorage/nim-codex
make_parallel: 4
nat_ip_auto: false
tag_latest: true
tag_sha: true
tag_suffix: ''
secrets: inherit
```
| Parameter       | Default                   |
| --------------- | ------------------------- |
| `docker_file`   | `docker/codex.Dockerfile` |
| `docker_repo`   | `codexstorage/nim-codex`  | …
=> Add reusable workflow for Docker

codex/stores/repostore.nim, tests/codex/stores/testrepostore.nim, tests/codex/testerasure.nim
Empty blocks were not retrievable by the RepoStore, and this was causing integration tests to fail when K > 1, as empty blocks were used for padding protected manifests. The failures, however, were only being witnessed on ARM64 (Apple silicon M2's and likely M1's, though untested), and not on AMD64, for reasons that are still unknown. @dryajov was looking into checking that the erasure coding was indeed being done correctly.
=> [repostore] Retrieve empty blocks

.github/workflows/docker-dist-tests.yml, .github/workflows/docker.yml
This is a quick fix for possible issue discovered by @AuHau when we can override `latest` tags with a builds from a custom branch. And now
- `tag_latest` will be set to true for `default branch`
- `tag_latest` will be set to true for `tagged commit`
I would like to review that behaviour in the future and I will reborn https://github.com/codex-storage/cs-codex-dist-tests/issues/42 slightly later.
=> Use latest tag for Tags and Default branch only

codex/contracts/requests.nim, codex/node.nim, codex/rest/api.nim, codex/rest/json.nim, codex/sales/reservations.nim, codex/utils/json.nim, tests/codex/testutils.nim, tests/codex/utils/testjson.nim, tests/integration/codexclient.nim, tests/integration/testIntegration.nim, tests/integration/testproofs.nim
The current client used for integration testing against the REST endpoints for Codex accepts and passes primitive types. This caused a hard to diagnose bug where a `uint` was not being deserialized correctly.
In addition, the json de/serializing done between the CodexClient and REST client was not easy to read and was not tested.
These changes bring non-primitive types to most of the CodexClient functions, allowing us to lean on the compiler to ensure we're providing correct typings when doing integration testing. More importantly, a json de/serialization util was created as a drop-in replacement for the std/json lib, with the main two differences being that field serialization is opt-in (instead of opt-out as in the case of json_serialization) and serialization errors are captured and …
=> Improve integration testing client (CodexClient) and json serialization

codex/stores/maintenance.nim, tests/integration/testblockexpiration.nim
This combined with https://github.com/codex-storage/nim-codex/pull/536 have greatly improved node stability and network stability in the continuous testing environment.
=> Slows down block maintenance iteration

codex/sales.nim, codex/sales/salescontext.nim, codex/sales/states/filled.nim, tests/codex/sales/testsales.nim
Closes #532.
Since the `onSale` callback can potentially be overridden (for example, like in [`testsales`](https://github.com/codex-storage/nim-codex/blob/9c487d9f028db4e59e3efa96bbf2806baf160a04/tests/codex/sales/testsales.nim#L408)), I have decided to create a new `onFilled` function instead. This function is not public and should only be used to clear the futures of the Queue.
Other options include making the `onSale` function "private" or supporting multiple functions in hooks.
=> fix: sales concurrency bug

docker/docker-compose.yaml
I was playing around with Codex and noticed the `datadir` is created in root (i.e. `/`) of my disk, which is not great.
This PR moves the `datadir` to `docker/` folder when you run something like
```
docker-compose -f docker/docker-compose.yaml up
```
I am also adding `:z` which is useful when you use SELinux to properly label the volume  (https://prefetch.net/blog/2017/09/30/using-docker-volumes-on-selinux-enabled-servers/)
=> chore: move the docker-compose volume

.github/workflows/ci.yml
This is an attempt to fix the issue reported by @tbekas with the Codecov data upload - [Upload coverage data to Codecov](https://github.com/codex-storage/nim-codex/actions/runs/6558809503/job/17814929442).
The issue is discussed here - ["Unable to locate build via Github Actions API" for the public repository #837](https://github.com/codecov/codecov-action/issues/837) and per [description](https://github.com/codecov/codecov-action/issues/837#issuecomment-1453877750) is related to the `GitHub's rate-limiting policy`.
Also discussion started on the Community board - [Upload Issues (`Unable to locate build via Github Actions API`)](https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954), but it is archived.
Current solution is to use token for …
=> Use token for coverage data upload to Codecov

codex/contracts/market.nim, codex/purchasing/states/cancelled.nim, codex/purchasing/states/error.nim, codex/purchasing/states/finished.nim, codex/purchasing/states/started.nim, codex/purchasing/states/submitted.nim, codex/sales/states/cancelled.nim, codex/sales/states/errored.nim, codex/sales/states/failed.nim, codex/sales/states/filled.nim, codex/sales/states/filling.nim, codex/sales/states/finished.nim, codex/sales/states/ignored.nim, codex/sales/states/initialproving.nim, codex/sales/states/payout.nim, codex/sales/states/preparing.nim, codex/sales/states/proving.nim, codex/sales/states/unknown.nim, tests/codex/testpurchasing.nim
Adds some basic logging for the purchases state machine following how it is done in sales.
=> chore(logging): purchases logging

tests/codex/sales/testsales.nim
Example of it failing: https://github.com/codex-storage/nim-codex/actions/runs/6572061624/job/17852429778#step:4:430
=> [sales] Fix intermittently failing test

codex/contracts/requests.nim, codex/purchasing/states/cancelled.nim, codex/purchasing/states/submitted.nim, codex/sales/salesagent.nim, codex/sales/states/cancelled.nim, codex/sales/states/failed.nim, codex/sales/states/unknown.nim, tests/codex/sales/testsales.nim, tests/codex/testpurchasing.nim, tests/examples.nim, tests/integration/codexclient.nim, tests/integration/testIntegration.nim
Adds support for partial payouts of canceled requests.
Also closes #556 and fixes off-by-one bug for calling `withdrawFunds()` contract function for canceled requests which leads to errors "Request is not expired yet".
The integration test is failing, though, because of the Hardhat's mining mode - automine. The time needs to be advanced (eq. mined block) before calling the `withdrawFunds()` function for the canceled request, but I have not figured out any way how to do it in the test's code. I have tried switching the Hardhat's mining mode into mining block every second and for that the test worked. Maybe we should consider changing the mining mode? It had brought us more problems recently 😳
The PR is blocked by the contract's PR: …
=> feat: partial payouts for cancelled requests

tests/integration/multinodes.nim, tests/integration/testblockexpiration.nim, tests/integration/testproofs.nim, tests/integration/twonodes.nim
When I run integration tests on my Mac with some security enabled I get:
This fixes it by listening on localhost instead of `0.0.0.0` which is a no-no for macOS 😅
=> test: integration tests listen on localhost

codex/codex.nim, codex/conf.nim, config.nims, tests/contracts/testContracts.nim, tests/contracts/testMarket.nim
Closes #554.
As in #554, this supports logging to a file, however in this PR, it is accomplished via a dynamic Chronicle's sink. The reason for a dynamic sink (`textlines[dynamic]`) is so that file logging can be disabled, because Chronicles' default behavior for `textlines[file]` is to log to a default file.
The main drawback, as discussed in #554 is that the file is not closed, which is no better than Chronicles. I did attempt to return the opened file from `setupLogging` and subsequently close it (on SIGINT and SIGTERM), however Chronicles continues to log past these events, so handling of file close would need to come after Chronicles is done with it (I'm not entirely sure if this is doable).
=> Support logging to file

codex/codex.nim, codex/contracts/interactions/interactions.nim, codex/node.nim, codex/rest/api.nim, openapi.yaml, tests/integration/codexclient.nim, tests/integration/testIntegration.nim
This PR makes the `expiry` parameter of the `requestStorage` API call mandatory, as it is not trivial to estimate it so we are "offloading" this to the user.
As I wanted to check that the "expiry is in future", I had to refactor `node.nim` to have the `clock` instance directly there and available in the API handler.
The branch is based on the `feat/set-ttl-for-requests-expiry` because of the changes to the `Clock` interface there.
Closes #611
=> fix: require expiry from api

codex/errors.nim, codex/node.nim, codex/node/batch.nim, codex/sales/states/downloading.nim, tests/codex/testnode.nim, tests/examples.nim
This is follow up PR after #619 which refactors the updating expiry part, moving it from `fetchBatched` into separate `onBatch` wrapper.
=> refactor: move expiry update from fetchBatched

codex/rest/api.nim, tests/integration/testIntegration.nim
Ensures that specified expiry is before requests end.
Related https://github.com/codex-storage/codex-contracts-eth/pull/77
=> fix: check expiration is before request end

codex/sales.nim, codex/sales/states/proving.nim
In proving.onCancelled, the `waitFor state.loop.cancelAndWait()` was never completing. Turns out this was not needed, because when changing states, the current state's run is cancelled, which automatically cancels the state prove loop, because it is a child of proving.run. Therefore, the logic to cancelAndWait the prove loop was removed as it was not needed.
This is a PR that is a smaller chunk of https://github.com/codex-storage/nim-codex/pull/607 to attempt to make it smaller and more digestible.
=> remove waitFor cancelAndWait in proving state

codex/sales.nim, codex/sales/reservations.nim, codex/sales/salesagent.nim, codex/sales/states/cancelled.nim, codex/sales/states/errored.nim, tests/codex/sales/testreservations.nim, tests/codex/sales/testsales.nim
This pull request brings the final piece to close issue #411 with a naive implementation. It introduces the concept of "returning bytes to availability," which is done for failed sales. This is achieved by attempting to re-reserve the required bytes from the Repo store. If successful, the bytes are returned; otherwise, an error is logged and the availability is lost.
I am unsure about the API of the `returnBytes` function, so please let me know in the review if you prefer it as it is.
There will be follow-up work later on that will intelligently handle the returning of bytes using a currently non-existing mechanism in RepoStore. This mechanism will clean up space for us when it is full, in order to avoid losing availability. This is partially addressed in the following link: …
=> feat: cleanup returning availability

tests/contracts/testClock.nim, tests/contracts/testContracts.nim, tests/contracts/testMarket.nim, tests/ethertest.nim, tests/integration/multinodes.nim, tests/integration/testIntegration.nim, tests/integration/testproofs.nim
To support more than two levels of integration test suite template nesting, `provider` had to be renamed to `ethProvider`, otherwise the compiler would complain that the `provider` symbol was unidentified in the top-most level of the nested test suites.
Eg
- `ethersuite`: declares `provider`
- `multinodesuite`
- `marketplacesuite` (`provider` symbol can't be found)
Note:
1. `marketplacesuite` does not exist yet; it is introduced in https://github.com/codex-storage/nim-codex/pull/607.
2. This PR is part of reducing the size of a much larger PR https://github.com/codex-storage/nim-codex/pull/607.
=> fix: rename `provider` to `ethProvider` in tests

codex/sales.nim
The Sales module was not marked as `running`, causing a hang in [multi node integration tests](https://github.com/codex-storage/nim-codex/pull/607).
This PR is to help break up a much larger PR (https://github.com/codex-storage/nim-codex/pull/607)
=> fix: sales module never marked as running, causing a hang

codex/contracts/market.nim, codex/market.nim, codex/utils/asyncstatemachine.nim, codex/validation.nim, tests/codex/helpers/mockmarket.nim
1. Add downtime information to the validator logs that provides information that proofs were not marked as missing due to being in downtime. This can help understand why proofs were not marked as missing.
2. Add previous state to the state machine transition log. This helps when debugging, particularly when entering the errored state, eg `SaleErrored`.
This PR is part of reducing the size of a much larger PR: https://github.com/codex-storage/nim-codex/pull/607
=> chore: improve log information

.github/workflows/docker-reusable.yml
`codex-storage/cs-codex-dist-tests/.github/workflows/continuous-tests.yaml` was renamed to `codex-storage/cs-codex-dist-tests/.github/workflows/run-continuous-tests.yaml` on master.
=> Updates reference to continuous tests workflow in cs-codex-dist-tests

.github/workflows/docker-dist-tests.yml, build.nims, codex/conf.nim, codex/contracts/clock.nim, config.nims, tests/contracts/testClock.nim, tests/integration/testIntegration.nim
Likely due to a Hardhat bug in which the callbacks for subscription events are called and awaited before updating its local understanding of the last block time, Hardhat will report a block time in the `newHeads` event that is generally 1 second before the time reported from `getLatestBlock.timestamp`. This was causing issues with the OnChainClock's offset and therefore the `now()` used by the `OnChainClock` would sometimes be off by a second (or more), causing tests to fail.
This commit introduce a `codex_use_hardhat` compilation flag, that when set, will always get the latest block timestamp from Hardhat via the `getLatestBlock.timestamp` RPC call for `OnChainClock.now` calls. Otherwise, the last block timestamp reported in the `newHeads` event will be used.
Update the docker dist tests …
=> Workaround for Hardhat last block timestamp bug

tests/integration/testIntegration.nim
Temporarily removing the partial payout integration test for now as it occasionally fails on macos/linux. This test has been completely refactored in PR https://github.com/codex-storage/nim-codex/pull/607 in which it will be reintroduced.
=> temporarily remove failing integration test

tests/integration/testIntegration.nim
`skip` seems to working only sometimes. It intermittently fails on Windows in CI. The reason for skipping the test in the first place was to prevent intermittent failures of the test itself, so adding `skip` did not improve the situation, unfortunately.
=> fix: comment out, instead of skipping, intermittently failing test

.github/actions/nimbus-build-system/action.yml, .github/workflows/ci.yml, .github/workflows/docker-reusable.yml, .github/workflows/docs.yml
We have a lot of `node 16` deprecation warnings in the GitHub Actions.
PR updates all actions to the latest major versions and almost all of them in the release notes mentions node version upgrade.
We probably should perform same update in other repositories as well.
=> Update actions to lates major versions

.github/workflows/docker-reusable.yml
This is a fix for the https://github.com/codex-storage/nim-codex/pull/688, where `actions/upload-artifact@v4` can't upload anymore artifacts under the same path.
Docker workflow is triggered only on master merge and the issue was not observed initially.
Tested by [manual run](https://github.com/codex-storage/nim-codex/actions/runs/7699072349) and Docker image was created
```
docker pull codexstorage/nim-codex:sha-bab1a5d-dist-tests
```
=> Fix Docker workflow after actions update

README.md, codex/conf.nim
These are spelling changes for `codex --help` to remove extra dots and readme was updated with a current output.
=> Update Codex help output

codex/conf.nim
We already discussed that for consistency it make sense to use the same length for the `Codex revision` as GitHub short commit. Currently we short it to the 6 characters (for some reason?) and GitHub shows 7.
```shell
codex --version
Codex version:  untagged build
Codex revision: ae61c2
Nim Compiler Version 1.6.14 [Linux: amd64]
```
We use [`git rev-parse --short HEAD`](https://github.com/codex-storage/nim-codex/blob/master/codex/conf.nim#L293-L297) and accordingly to the [documentation](https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---shortlength)
> `--short[=length]`
> Same as `--verify` but shortens the object name to a unique prefix with at least `length` characters. The minimum length is 4, the default is the effective value of the `core.abbrev` configuration …
=> fix: use default short commit length for codex revision

codex/clock.nim, codex/contracts/clock.nim, codex/purchasing.nim, codex/rest/api.nim, codex/sales/salesagent.nim, codex/sales/states/proving.nim, codex/stores/maintenance.nim, codex/stores/repostore.nim, codex/systemclock.nim, codex/validation.nim, tests/codex/helpers/mockclock.nim, tests/codex/node/testcontracts.nim, tests/codex/sales/testsales.nim, tests/codex/testpurchasing.nim, tests/codex/testsystemclock.nim, tests/codex/testvalidation.nim, tests/contracts/testClock.nim
`clock.now` is the last method of `Clock` that isn't yet async. The requirement for an async `clock.now` [already exists in test code](https://github.com/codex-storage/nim-codex/blob/master/codex/contracts/clock.nim#L54), but we've been avoiding making that change and have so far instead resorted to using `waitFor` and maintaining a non-async signature. This is however not recommended, and it breaks the profiler.
This PR makes the required changes so that clock.now becomes async. The alternative is figuring out a different way to implement the test so that the `waitFor` call is no longer required, and then we can kick the can down the road.
=> remove call to `waitFor` from clock.now and make it async

.github/workflows/ci-reusable.yml, .github/workflows/ci.yml, .github/workflows/docker-reusable.yml, .github/workflows/nim-matrix.yml
In PR [Build improvements #680](680), we raised the question about building Codex using different Nim versions, but **only before the merge** to not slow-down existing PR flow and to not waste resources on every push.
We can try to use [GitHub merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) to implement that.
- Add `build-status` job to `CI` workflow to check matrix execution status - will use it in branch rule
- Add `Nim-matrix` workflow to **run only on merge queue** and only on Linux
- [Using concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) for `CI` workflow to cancel previous run at PR next commits
- Are we ready for experiments ? 😄
- Merge
- …
=> Add Nim-matrix workflow to run on merge queue

codex/contracts/config.nim, codex/contracts/deployment.nim, codex/contracts/market.nim, codex/contracts/marketplace.nim, codex/contracts/proofs.nim, codex/market.nim, codex/node.nim, codex/sales/salescontext.nim, codex/sales/states/filling.nim, codex/sales/states/proving.nim, codex/sales/states/provingsimulated.nim, tests/codex/helpers/mockmarket.nim, tests/codex/sales/states/testfilled.nim, tests/codex/sales/states/testinitialproving.nim, tests/codex/sales/states/testproving.nim, tests/codex/sales/states/testsimulatedproving.nim, tests/codex/sales/testsales.nim, tests/codex/testvalidation.nim, tests/contracts/deployment.nim, tests/contracts/testContracts.nim, tests/contracts/testDeployment.nim, tests/contracts/testMarket.nim, tests/examples.nim, tests/integration/multinodes.nim, tests/integration/testproofs.nim
Updates the smart contracts to use the ZK verifier. Proof is now modeled as a Groth16Proof struct instead of a sequence of bytes.
Closes #684
=> Smart contracts update: Groth16Proof instead of bytes

codex/erasure/erasure.nim, codex/indexingstrategy.nim, codex/slots/builder/builder.nim, codex/utils/asynciter.nim, tests/codex/slots/provingtestenv.nim, tests/codex/slots/testslotbuilder.nim, tests/codex/testindexingstrategy.nim
Reworks the indexer as an enum, to allow saving the strategy in the manifest.
Changes split out of #686 for easier tracking.
=> rework indexing strategy to use an enum

.github/workflows/ci-reusable.yml, docker/codex.Dockerfile
PR install Rust for Docker builds.
Also, `NIMBLE_DIR` was removed from `PATH` via `"${HOME}/.bash_env"` - not sure how this is intended to work.
Was [tested manually](https://github.com/codex-storage/nim-codex/actions/runs/7854380843).
```shell
docker run codexstorage/nim-codex:sha-a0761bb-dist-tests codex --version
Codex version:  untagged build
Codex revision: a0761bb
Nim Compiler Version 1.6.14 [Linux: arm64]
```
=> Install Rust during Docker builds

docker/docker-entrypoint.sh
This is a quick fix for existing Docker entrypoint
Since we've introduced [`NAT_PUBLIC_IP_AUTO`](https://github.com/codex-storage/nim-codex/commit/750fe2392feb57e6043b824e8e939a99d866e30a) helper variable in Docker entrypoint, we broke image run with default values
```shell
docker run codexstorage/nim-codex:latest
docker run -e NAT_IP_AUTO=true codexstorage/nim-codex:latest
docker run -e NAT_PUBLIC_IP_AUTO=ip.codex.storage codexstorage/nim-codex:latest
```
In this PR, we use slightly different logic
1. When `CODEX_NAT` is passed - use it
2. `NAT_PUBLIC_IP_AUTO` (Public IP) have priority over `NAT_IP_AUTO`(Private IP)
3. Show separate error for `NAT_PUBLIC_IP_AUTO` and `NAT_IP_AUTO` when can't get IP address
=> Fix Docker entrypoint NAT helper variables

codex/clock.nim, codex/contracts/clock.nim, codex/purchasing.nim, codex/rest/api.nim, codex/sales/salesagent.nim, codex/sales/states/proving.nim, codex/stores/maintenance.nim, codex/stores/repostore.nim, codex/systemclock.nim, codex/validation.nim, tests/codex/helpers/mockclock.nim, tests/codex/node/testcontracts.nim, tests/codex/sales/testsales.nim, tests/codex/testpurchasing.nim, tests/codex/testsystemclock.nim, tests/codex/testvalidation.nim, tests/contracts/testClock.nim
This reverts commit 591be9446a5cee1ce559c87e496fa4d7dab92924.
The purpose of this reversion is to make way for https://github.com/codex-storage/nim-codex/pull/662, in which the integration tests do not work with `clock.now` being async.
Once reverted, and with the integration tests from #662 merged, we can figure out why the async clock fails the tests and figure out a fix.
=> Revert "remove call to `waitFor` from clock.now and make it async (#691)

.github/workflows/ci-reusable.yml, .github/workflows/ci.yml, .gitignore, codex/node.nim, codex/purchasing/states/submitted.nim, codex/sales/states/downloading.nim, codex/sales/states/filling.nim, codex/sales/states/proving.nim, codex/sales/states/provingsimulated.nim, tests/examples.nim, tests/integration/clioption.nim, tests/integration/codexclient.nim, tests/integration/codexconfig.nim, tests/integration/codexprocess.nim, tests/integration/hardhatconfig.nim, tests/integration/hardhatprocess.nim, tests/integration/marketplacesuite.nim, tests/integration/multinodes.nim, tests/integration/nodeconfig.nim, tests/integration/nodeprocess.nim, tests/integration/testIntegration.nim, tests/integration/testmarketplace.nim, tests/integration/testproofs.nim, tests/testIntegration.nim
Closes https://github.com/codex-storage/nim-codex/issues/594
Refactor the multinode test suite into the marketplace test suite.
- Arbitrary number of nodes can be started with each test: clients, providers, validators
- Hardhat can also be started locally with each test, usually for the purpose of saving and inspecting its log file.
- Log files for all nodes can be persisted on disk, with configuration at the test-level
- Log files, if persisted (as specified in the test), will be persisted to a CI artifact
- Node config is specified at the test-level instead of the suite-level
- Node/Hardhat process starting/stopping is now async, and runs much faster
- Per-node config includes:
- simulating proof failures
- logging to file
- log level
- log topics
- storage quota
- debug (print logs to …
=> refactor: multinode integration test refactor

.github/workflows/ci-reusable.yml
This is a follow up of the #688.
In #662 we introduced one more actions with a [deprecation warning](https://github.com/codex-storage/nim-codex/actions/runs/7954945496).
=> ci: update actions to the latest major versions

.github/workflows/ci.yml
PR update macOS runner to the latest amd64 version, which is `macos-13`. Previous one is `macos-latest = macOS 12`.
[GitHub Actions: macOS 14 (Sonoma) is now available](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/)
> The macOS 12 runner image will remain `latest` until migration of the latest YAML workflow label to macOS 14 in Q2 FY24 (April – June 2024). While macOS 13 is now generally available under the `macos-13` label, this image **will not be migrated to `latest`**.
Experiments shows, that `macos-13` probably is faster than `macos-latest` (4 vs 3 CPU) and at least not slower than Windows integrations tests. If it will help us to save 10 minutes per run, it is not so bad.
<details>
<summary>details</summary>
[Standard GitHub-hosted runners …
=> ci: use latest amd64 macos runner

codex/blockexchange/engine/engine.nim, codex/blockexchange/network/network.nim, codex/utils.nim, tests/codex/blockexchange/engine/testblockexc.nim, tests/codex/blockexchange/engine/testengine.nim, tests/codex/helpers.nim, tests/codex/helpers/nodeutils.nim, tests/codex/utils/testutils.nim
This PR fixes the active cancellation of pending want requests by adding the actual want list sends with the `cancel` flag set to true as part of block delivery, with accompanying tests.
=> Fixes active cancellation for pending want requests

BUILDING.md, docker/codex.Dockerfile, docker/docker-entrypoint.sh
**BUILDING.md** - [preview](https://github.com/codex-storage/nim-codex/blob/docs/update-building-codex/BUILDING.md)
- Prettify documentation
- Make documentation copy/paste friendly
- Add rust related packages for Linux/macOS
**docker/docker-entrypoint.sh**
- Add auto-export
- Unify variables enclosure
**docker/codex.Dockerfile**
- Switch to `ubuntu:22.04` image, because
- we use same version on GitHub Actions CI
- the previous one is `ubuntu:lunar-20230415` - [Ubuntu 23.04 is EOL](https://wiki.ubuntu.com/Releases) on 25 January 2024
- We do not need to install `nim` - `nimbus-build-system` will take care about that
- Install `rust` and `cargo` via package manager
- Install `jq` to be used with already installed `curl`
=> Update Docker files and building Codex docs

codex.nim, codex/codex.nim
fixes #726 
fixes #725 (in part)
fixes #705 
fixes #640 
This PR fixes Codex's startup sequence so it does proper error handling and doesn't simply hang when something goes wrong. It essentially deals with the errors in the main module, making it effectively the supervisor for these ops. As a sidenote, all service loops (and critical ops) should be supervised - there's still plenty of opportunity for us to go into zombie mode as internal services crash with no-one to see or deal with the failures.
=> Abort Codex when startup sequence fails

codex/contracts/clock.nim, codex/contracts/market.nim, tests/contracts/testClock.nim, tests/contracts/time.nim, tests/ethertest.nim, tests/integration/multinodes.nim, tests/integration/testmarketplace.nim, tests/integration/testproofs.nim
Fixes on-chain clock to deal with the weird behaviour that Hardhat shows. It appears that Hardhat is calling the 'newHeads'  callback for pending blocks. This works around the issue by only looking at the 'latest' block, and by only processing blocks once.
Extracted from #702
Depends on #731
=> Fix on-chain clock

codex/purchasing/states/started.nim, codex/sales/salesagent.nim, codex/sales/states/proving.nim, tests/codex/sales/states/testproving.nim, tests/codex/sales/states/testsimulatedproving.nim, tests/codex/sales/testsalesagent.nim, tests/codex/testpurchasing.nim, tests/codex/testsales.nim
Fixes a number of things in the sales agent:
- only act upon timeouts when really inside a new period (period start + 1 second)
- fixes issue with onCancelled and onFailed not being called
- fixes issue where the cancellation loop would continue running when request starts
- fixes the salesagent tests, which weren't being run 
Extracted from #702 
Depends on #732
=> Fix sales agent

codex/blockexchange/engine/engine.nim, codex/node.nim, tests/codex/node/helpers.nim, tests/codex/node/testnode.nim
fixes #699 
`CodexNodeRef.retrieve` always tried to refetch manifests for which `fetchManifest` fails, even if these failures were not due to decoding errors (which would indicate that the CID was pointing to a block which was not a manifest) but timeouts (which would indicate that the CID does not exist, and we should just return with a failure).
This means that, if the CID does not exist, we had to wait for twice the timeout (currently 20 minutes) before getting an error. This PR fixes that, so that we lookup only once and the actual timeout is respected.
=> fixes double lookups when block does not exist

codex/contracts/market.nim, codex/market.nim, codex/sales/states/provingsimulated.nim
Add MarketError and convert all EthersErrors (ProviderError, SignerError) to MarketError
Based on branch of PR #662.
=> refactor: add MarketError

docker/codex.Dockerfile
This PR includes the openapi.yaml in our docker images.
This makes it so that each docker image contains the machine-readable documentation for how to use that image.
This enables some convenient automation:
- Client-code to be generated from the yaml
- Guaranteed compatibility or compatibility checking when using docker images of different versions of Codex
=> Include openapi yaml in docker image

openapi.yaml
'number' can be a float or double.
This would sometimes cause trouble for serialization/deserialization of API calls.
=> Replace 'number' with 'integer' in openapi spec

codex/rest/api.nim, docs/TWOCLIENTTEST.md, openapi.yaml
Adds a text only API endpoint `curl http://127.0.0.1:8080/api/codex/v1/spr` to simplify curl commands.
Question, when `node.discovery.dhtRecord.isSome` is empty what should we do? I followed the debug info and return empty string 204 status code. Though perhaps it should be an error, maybe a 503?
Implements https://github.com/orgs/codex-storage/projects/3/views/9?pane=issue&itemId=57116903
=> Add Node SPR endpoint

codex/discovery.nim
This PR **temporarily** disables per-k-bucket and aggregate routing table IP limits on the discv5 DHT until we figure out how to make those play nice with heavily NATed environments (think room full of people at a Codex workshop).
Follow up issue to handle this issue in a more sensible manner [here](https://github.com/orgs/codex-storage/projects/3/views/9?pane=issue&itemId=58252879).
=> Disable Discv5 bucket and routing table IP limits

codex/blockexchange/engine/engine.nim, tests/codex/blockexchange/engine/testengine.nim
Current implementation announces every local block to the DHT.
Only the treeCID and manifestCID are used for discovery.
=> Announce to DHT only tree and manifest CIDs

codex/manifest/coders.nim, tests/codex/testmanifest.nim
Something strange is happening to manifests that describe large datasets when they are encoded/decoded into blocks.
The datasetSize parameter never comes out right when the dataset is 5GB or larger.
Traced the issue to: uint32 is used in protobuf-encoding for datasetSize parameters.
5GB in bytes = 5.368.709.120
uint32 max = 4.294.967.295
This PR bumps those to uint64s.
=> Bug: Large manifests encoding

codex/blockexchange/engine/discovery.nim, tests/codex/blockexchange/discovery/testdiscovery.nim, tests/codex/blockexchange/discovery/testdiscoveryengine.nim
This updates the advertising loop in the discovery engine to advertise only manifest CIDs and tree CIDs.
Current implementation advertises every block, and does NOT advertise trees.
=> Advertise manifests and trees

codex/contracts/market.nim, codex/contracts/marketplace.nim, codex/purchasing/states/pending.nim, tests/contracts/testContracts.nim, tests/contracts/testMarket.nim
This is a follow-up fix PR for #793.
The `purchasing` module had an issue because `requestStorage` was called, and a transaction to the blockchain was created. Right away, the state machine transitioned from `pending` to `submitted` state. However, the last PR added a call to the blockchain in the `submitted` state, which requires the transaction to be already mined. This PR ensures that with a requiring confirmation of one block.
After a discussion with Mark, we agreed that we should add confirmation of one block to all transaction creation calls. Mainly because the `Market` abstraction sort of communicates that "when a call to its method finishes, then it is final". Having created a transaction that might not be included in the blockchain is not "final", hence the one confirmation.
=> feat: one confirmation for all transactions

codex/sales.nim, codex/sales/reservations.nim, codex/sales/salesagent.nim, codex/sales/slotqueue.nim, codex/sales/states/cancelled.nim, codex/sales/states/downloading.nim, codex/sales/states/errored.nim, codex/sales/states/ignored.nim, codex/utils/asyncheapqueue.nim, tests/codex/helpers/mockslotqueueitem.nim, tests/codex/sales/states/testcancelled.nim, tests/codex/sales/states/testdownloading.nim, tests/codex/sales/states/testerrored.nim, tests/codex/sales/states/testignored.nim, tests/codex/sales/testreservations.nim, tests/codex/sales/testsales.nim, tests/codex/sales/testslotqueue.nim
Adds slot queue pausing based on the design in https://github.com/codex-storage/codex-research/pull/188.
@AuHau -- I took the changes in commit https://github.com/codex-storage/nim-codex/pull/748/commits/1425bf5c3f42a80f16821789af7957d4757f1e17 and added to this PR as I needed to update that routine.
Close #549
=> feat[marketplace]: add slot queue pausing

.github/actions/nimbus-build-system/action.yml, .github/workflows/release.yml, BUILDING.md
PR adds a simple release workflow which will build binaries and attach them to the release
- Update Rust requirements in the Building guide
- It was required to adjust composite action [nimbus-build-system](https://github.com/codex-storage/nim-codex/tree/master/.github/actions/nimbus-build-system) to add Linux arm64 support
- In a composite action we also install specific Rust version, because BuildJet one is out of date
- Small refactoring of the composite action to make code more readable
- Release workflow added
- Use all free available architectures on GitHub Actions
- For Linux ARM use BuildJet
- Include version in the binaries names
- Pack binaries to minimize the size
- Experimenting with the uploading binaries to the Codex Testnet nodes
> **Note:** Window arm64 runners will be …
=> Add Release workflow

openapi.yaml
JSON deserialize fails:
OpenAPI spec defines int32s, but values exceed int32.max.
This fix: Sets spec to int64s wherever we are counting bytes.
=> Sets int64 formats for byte-counting integers in openapi spec

codex/erasure/erasure.nim, codex/indexingstrategy.nim, codex/node.nim, codex/stores/cachestore.nim, codex/stores/queryiterhelper.nim, codex/stores/treehelper.nim, codex/utils/asynciter.nim, codex/utils/iter.nim, tests/codex/stores/testqueryiterhelper.nim, tests/codex/teststores.nim, tests/codex/testutils.nim, tests/codex/utils/testasynciter.nim, tests/codex/utils/testiter.nim
* Separate modules for `AsyncIter[T]` and `Iter[T]`
* Tests for both `asynciter.nim` and `iter.nim`
* Helper methods for converting from `QueryIter` to `AsyncIter`
=> Rework AsyncIter

.github/workflows/ci-reusable.yml, .github/workflows/ci.yml
Currently, our CI will build branches against a PR's "merge" commit, which is a commit that previews the merge of the current branch against master. This can result in very surprising behavior, and I'd argue it's not what we typically want.
This PR modifies the CI flow so that it uses HEAD instead.
=> Make CI build against branch HEAD instead of merge

codex/codex.nim, codex/conf.nim, codex/rest/api.nim
This is needed when downloading data from a browser, eg the [ethcc-demo](https://github.com/codex-storage/ethcc-demo)
=> config flag to enable CORS response headers for data downloads

.github/workflows/ci.yml, .github/workflows/nim-matrix.yml, Makefile
This PR introduces the ability to pin a compiler version (major or minor) so that we get consistent builds locally, in docker, and in CI.
The compiler version can be overridden by setting the `NIM_COMMIT` env variable as before to either a compiler version, branch, or commit hash, but we also introduce the following special semantics for `NIM_COMMIT`:
* if unset, uses the pinned version;
* if set to `pinned`, uses the pinned version (so that CI can specify it wants the pinned version in a matrix);
* if set to `nimbusbuild`, uses the version defined by the nimbus-build-system.
In case you need more convincing, the original reasoning for doing this [can be found here](https://hackmd.io/2dp6Q2tmQzWoKN-dIPckTQ).
=> Allow compiler version to be pinned consistently

codex/manifest/manifest.nim, codex/streams/storestream.nim, tests/codex/teststorestream.nim
This PR fixes `StoreStream` so it doesn't return parity bytes when one attempts to download a file by the CID of a protected of verifiable manifest. It also drops the `pad` option which was not used anywhere.
=> Fix StoreStream so it doesn't return parity bytes 

.github/workflows/release.yml
As we discussed with @benbierens and @gmega, it make sense to add `-d:verify_circuit=true` to the releases
> This way we can check if proofs are invalid when they are created, or whether the validation fails on-chain
This is a quick PR to adjust release workflow for that.
=> Add verify_circuit=true to the releases

codex/node.nim
This PR **hacks** Codex so that it catches defect on erasure code decode and stops the node from crashing. This is not an acceptable fix for the issue, and should be removed as soon as we fix the actual bug.
=> Provisional fix so EC errors do not crash the node on download

codex/node.nim
Node was crashing with:
```
TRC 2024-06-26 12:38:07.334+10:00 Unable to erasure decode manifest          topics="codex node" tid=25906173 manifestCid=zDv*Zkg5qb exc="Original tree root differs from the tree root computed out of recovered data"
ERR 2024-06-26 12:38:07.334+10:00 Unhandled exception in async proc, aborting topics="codex" tid=25906173 msg="/Users/egonat/repos/codex-storage/nim-codex/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim(133, 5) `not val.isNil` "
```
=> [BUG] prevent node crashing with `not val.isNil`

codex/erasure/erasure.nim, codex/rest/api.nim, tests/integration/codexclient.nim, tests/integration/testpurchasing.nim, tests/integration/testrestapi.nim
During our testing for the workshop, we noticed there were many instances arises from lack of constraints about dataset size and erasure coding parameters, that ultimately caused issues erasure decoding once the requests for storage had been created. Some of these constraints are due to limitations of Leopard, the underlying lib used for erasure coding. Attempting to erasure decode datasets that had been poorly constructed, but accepted as valid by the Codex node, causes quite a few crashes.
While this PR only addresses constraining the parameters for the REST API, further measures may be needed in the contracts.
=> feat(rest): adds erasure coding constraints when requesting storage

.github/workflows/release.yml
PR updates Release workflow and adds the following changes
- Switch workflow to the pinned Nim version introduced in #832
- Add Windows builds with attached libraries - `codex-v0.1.3-windows-amd64-libs.zip`
- Remove experimental code to upload binaries to the Codex network
- Set execution bits for Linux/macOS binaries
- Upload final artifacts to the job - useful to get archives and checksum from a branch and upload to a release, now we do that for [feature/ceremony-files](https://github.com/codex-storage/nim-codex/tree/feature/ceremony-files) manually
- Upload artifacts to a release only for git tags - this helps to not fail when run on a branch
=> Update Release workflow

.github/actions/nimbus-build-system/action.yml, .github/workflows/ci-reusable.yml
This is a quick and temporary fix until we will fix all dependencies to work with gcc 14.
@benbierens is working on the dependencies
| Dependency                                                          | Status                                                                       |
| ------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`status-im/nim-bearssl`](https://github.com/status-im/nim-bearssl) | Update submodule                                                             |
| [`vacp2p/nim-libp2p`](https://github.com/vacp2p/nim-libp2p)         | [In progress](https://github.com/vacp2p/nim-libp2p/tree/multihash-poseidon2) |
| [`nim-leopard`](https://github.com/codex-storage/nim-leopard) …
=> Downgrade to gcc 13 on Windows

codex/rest/api.nim
This PR was created from the discussion in #866. 
The browser adds a content-type header when trying to upload the file, but the Codex client does not handle it. So this PR adds an OPTIONS endpoint to add this header and allow the preflight request.
=> Add OPTIONS endpoint to allow the content-type header for the upload endpoint

codex/contracts/config.nim, tests/codex/helpers/mockmarket.nim
Adds client support for https://github.com/codex-storage/codex-contracts-eth/issues/108.
Related to https://github.com/codex-storage/codex-contracts-eth/pull/138.
=> chore: add `downtimeProduct` config parameter

codex/rest/api.nim
When trying to create a new storage request with the API, the request can fail if the parameters are invalid due to some rules (for example, parameters must satisfy 1 < (nodes - tolerance) ≥ tolerance).
When the error is returned with the following code, the CORS headers are not included:
```
return RestApiResponse.error(Http400, error.msg)
```
This PR fix this issue and returns the CORS headers when the storage requests api returns an error.
=> Support CORS preflight requests when the storage request api returns an error 

codex/contracts/market.nim, codex/contracts/marketplace.nim, codex/market.nim, tests/codex/helpers/mockmarket.nim, tests/contracts/testMarket.nim
Allows querying of past Marketplace events using a generic routine.
Also moves marketplace contract events to the Market abstraction so the types can be shared across all modules that call the Market abstraction.
=> refactor(marketplace): generic querying of historical marketplace events

openapi.yaml
Fixes #894 
Removes fields that are no longer included in the `StorageRequest` object.
=> chore(openapi): remove erasure and por parameters from openapi spec

.github/workflows/ci-reusable.yml, docker/docker-entrypoint.sh
We recently discovered that existing [`docker-entrypoint.sh`](https://github.com/codex-storage/nim-codex/blob/264bfa17f54b7973432d000446a725a4b5a6134a/docker/docker-entrypoint.sh#L53-L66) does not support CLI arg for `cirld` and only env vars are supported. And in case when we run Codex only using args, it is required to pass additionally duplicate env vars for `cirdl`.
PR implements parsing of the CLI arguments and passes them to the `cirdl`.
=> Use CLI args when passed for cirdl in Docker entrypoint

codex/contracts/market.nim, codex/contracts/marketplace.nim, codex/market.nim
Closes #898.
These functions are not called yet. They are being implemented as part of a [longer list of tasks for slot reservations](https://github.com/codex-storage/codex-pm/issues/45) to prevent PRs from being too large.
Wire up `reserveSlot` and `canReserveSlot` contract calls, but don't call them
NOTE: This uses updated contracts pointing to a branch in https://github.com/codex-storage/codex-contracts-eth/pull/176. It's probably best to merge that PR first, then update this PR to point to the master branch of `codex-contracts-eth`
=> feat(slot-reservations): Support reserving slots

codex/contracts/market.nim, codex/sales/states/ignored.nim, codex/sales/states/preparing.nim, codex/sales/states/slotreserving.nim, tests/codex/helpers/mockmarket.nim, tests/codex/helpers/mockreservations.nim, tests/codex/sales/states/testignored.nim, tests/codex/sales/states/testpreparing.nim, tests/codex/sales/states/testslotreserving.nim, tests/codex/sales/teststates.nim
Closes #916
This is being implemented as part of a [longer list of tasks for slot reservations](https://github.com/codex-storage/codex-pm/issues/45) to prevent PRs from being too large.
Adds a new state, `SaleSlotReserving`, that attempts to reserve a slot before downloading.
If the slot cannot be reserved, the state moves to SaleIgnored.
On error, the state moves to `SaleErrored`.
`SaleIgnored` is also updated to pass in `reprocessSlot` and `returnBytes`, controlling the behaviour in the sales module after the slot is ignored. This is because previously it was assumed that SaleIgnored was only reached when there was no availability. This is no longer the case, since `SaleIgnored` can now be reached when a slot cannot be reserved.
=> feat(slot-reservations): Add SaleSlotReserving state

.github/workflows/release.yml
This PR address the issue #932 and we are using a workaround and run release builds for Linux amd64 on [Ubuntu 20.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md).
For arm64 builds, we miss such an option on [BuildJet](https://buildjet.com/for-github-actions/docs/runners/hardware#arm), and by the end of the yer, we expect to switch to the [GitHub arm64 runners](https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/). But it is not so clear now which Ubuntu versions will be available.
<details>
<summary>details</summary>
[About Ubuntu and Windows larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners#about-ubuntu-and-windows-larger …
=> Use Ubuntu 20.04 for Linux amd64 releases

codex/contracts/market.nim, codex/market.nim, codex/sales.nim, tests/codex/helpers/mockmarket.nim, tests/codex/sales/testsales.nim, tests/contracts/testMarket.nim
Closes #931.
This is being implemented as part of a [longer list of tasks for slot reservations](https://github.com/codex-storage/codex-pm/issues/45) to prevent PRs from being too large.
Subscribes to the `SlotReserverationsFull` contract event. Once the event is triggered, the slot is removed from the node's slot queue.
=> feat(slot-reservations): support SlotReservationsFull event

openapi.yaml
This PR is trying to improve the documentation for [space endpoint](https://api.codex.storage/#tag/Data/operation/space). It fixes #919.
=> docs(openapi): provider better documentation for space endpoint parameters

codex/contracts/deployment.nim
PR updates Codex Testnet marketplace address, to the new one just recently deployed 
- New Marketplace contract address: [`0xfE822Df439d987849a90B64a4C0e26a297DBD47F`](https://explorer.testnet.codex.storage/tx/0x9b8fa732174122641656b7159eb82f7bc5bf80541bae4bfc9fea0e7568210558)
- Version used for deployment: `codexstorage/codex-contracts-eth:sha-807fc97-dist-tests`
=> Update Codex Testnet marketplace contract address

tests/contracts/testContracts.nim, tests/contracts/testMarket.nim
Closes #933.
This is being implemented as part of a [longer list of tasks for slot reservations](https://github.com/codex-storage/codex-pm/issues/45) to prevent PRs from being too large.
The contracts changes included in this PR enforce that a slot is reserved before it is filled.
This PR adds support for these updates by updating the tests to reserve slots before filling them.
=> feat(slot-reservations): support enforcement of slot reservations before filling slot

codex/rest/api.nim
Currently, the REST endpoints don't return the CORS headers when they return an error.
One of the reasons is that Nim Presto has a weird behavior of adding the `Access-Control-Allow-Origin` header when a request is successful and omitting it when the request returns an error (see the method processRestRequest in nim-presto/presto/serverprivate.nim).
This PR fixes this behavior by adding the CORS headers whenever a response is returned. I was hesitant to create an `OPTIONS` endpoint for every request, as we did for the data upload, but it does not work with [simple requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests) because no `OPTIONS` request is sent by the browser in that case.
Without the CORS headers returned when an endpoint returns an error, I am unable …
=> fix(restapi): Add cors headers when the request is returning errors

tools/cirdl/cirdl.nim
Useful for debugging testnet cloud nodes.
=> Adds log to CIRDL to show URL

codex/contracts/market.nim, codex/sales/states/filling.nim, codex/sales/states/slotreserving.nim, codex/utils/asyncstatemachine.nim, tests/codex/sales/states/testfilling.nim, tests/codex/sales/states/testslotreserving.nim, tests/integration/hardhatprocess.nim, tests/integration/nodeprocess.nim
This PR does two things which we have seen cause issues in the testnet:
1. Avoids cancelled `SaleReserving` and `SaleFilling` states when slots are filled. The cancellations were bubbling into `nim-ethers` and causing issues with nonce management.
2. Improves logging for situations where a sale should be ignored instead of being considered an error, including when a reservation is not allowed and when a slot was filled by another host.
=> fix(slot-reservations): Avoid slot filled cancellations

codex/rest/api.nim
The following lines are not needed: 
```
if corsOrigin =? allowedOrigin:
resp.setCorsHeaders("GET", corsOrigin)
resp.setHeader("Access-Control-Headers", "X-Requested-With")
```
The reason is that the headers are explicitly added when the API returns an error response, but when the response is successful, nim-presto handles that. As a result, the previous lines are adding a duplicate Access-Control-Allow-Origin header in the browser, which raises an error.
This PR addresses this issue.
=> Remove duplicate cors header for fetch manifest endpoint 

docker/docker-entrypoint.sh
This is a quick PR to add `ETH_PRIVATE_KEY` to the Docker entrypoint for variables names consistency.
During transition period we can use both, `PRIV_KEY` and `ETH_PRIVATE_KEY`, to the pass Ethereum private key.
After we will change all the code to use new variable, the old one will be removed.
=> Add ETH_PRIVATE_KEY to Docker entrypoint

.github/workflows/ci-reusable.yml, .github/workflows/ci.yml
As we stated in the https://github.com/codex-storage/nim-codex/pull/993#issuecomment-2492976891, it make sense to check how tests split for Linux and macOS will improve CI run time.
PR add a split for Linux and macOS and we also adjusted jobs name to make it easier to distinguish them by tests type.
=> ci: split linux and macos tests

.github/workflows/ci-reusable.yml, codex/contracts/market.nim, tests/codex/testvalidation.nim, tests/contracts/testClock.nim, tests/contracts/testContracts.nim, tests/contracts/testMarket.nim, tests/contracts/time.nim, tests/ethertest.nim, tests/integration/multinodes.nim, tests/integration/testecbug.nim, tests/integration/testmarketplace.nim, tests/integration/testproofs.nim, tests/integration/testpurchasing.nim, tests/integration/testsales.nim, tests/integration/twonodes.nim, tests/tools/cirdl/testcirdl.nim
Switches nim-ethers to http subscriptions instead of websocket subscriptions. This changes the timing of subscriptions and unearths some concurrency issues. This PR fixes those issues.
Includes:
- fixes to nim-ethers: https://github.com/codex-storage/nim-ethers/pull/94
- transactions are confirmed with `.confirm(1)`, previously we used `.confirm(0)`, which didn't work
- many fixes to tests that had hidden assumptions about timing
This is split off from the work in #988
=> Fix concurrency issues

codex/contracts/deployment.nim
PR updates Marketplace contact address for Codex Testnet.
Part of  #1000.
=> chore: update testnet marketplace address

tests/codex/blockexchange/discovery/testdiscoveryengine.nim
Requesting the same CID sometimes causes a worker to discard the request while another worker has the same CID in-flight.
=> Fix race condition in testdiscoveryengine

docker/codex.Dockerfile
We've seen crashes without stack traces from cluster deployments. This should help with debugging.
=> Enables stacktrace in docker images

codex/contracts/clock.nim, codex/contracts/market.nim, tests/integration/testecbug.nim, tests/integration/testmarketplace.nim, tests/integration/testproofs.nim
Brings in a version of nim-ethers where subscription callbacks are returned Result, which will give an error when there is some underlying problem in the subscription mechanisms. This PR exposes these errors through logging.
=> feat: expose underlying nim-ethers errors to logs

.github/workflows/docker-dist-tests.yml, .github/workflows/docker-reusable.yml
This is a https://github.com/codex-storage/cs-codex-dist-tests/issues/108 follow up and it would be usefully to simplify release tests run via a "true" single button.
PR add an option to the [Docker - Dist-Tests](https://github.com/codex-storage/nim-codex/actions/workflows/docker-dist-tests.yml) workflow in nim-codex repository to be able to run release tests from [cs-codex-dist-tests](https://github.com/codex-storage/cs-codex-dist-tests) repository as a part of the Docker images build process.
=> Run release tests for docker images

codex/blockexchange/engine/engine.nim, codex/logutils.nim, tests/codex/blockexchange/discovery/testdiscoveryengine.nim
Previously:
```
discard await allFinished(
wantCids.mapIt(b.sendWantBlock(it, peerCtx)))
```
This gives 1 wantBlock message per entry in wantCid blockAddress. But, message format supports multiple addresses.
New:
```
await b.sendWantBlock(wantCids, peerCtx)
```
Todo, not in this PR: initial calls to send wantHave and wantBlock messages can be pluralized as well.
=> Send pluralized wantBlock messages

tests/codex/sales/testsales.nim
Removes an unneeded `check eventually` inside a helper proc, removing the need for the proc to be async.
=> chore(tests): fix unneeded async

Makefile, flake.lock, flake.nix, nix/README.md, nix/default.nix, nix/tools.nix
Create a structure for nix files. Add the derivation file which is using system Nim to compile Codex. Move shell definition to a specific file.
Referenced issue: https://github.com/codex-storage/nim-codex/issues/940
=> nix: make derivation and update shell

codex/contracts/market.nim, codex/contracts/requests.nim, codex/market.nim, codex/sales/states/filling.nim, codex/sales/states/preparing.nim, codex/sales/states/proving.nim, codex/sales/states/unknown.nim, tests/codex/helpers/mockmarket.nim, tests/contracts/testMarket.nim
Adds support for changes in the contract that introduce repair reward as described here: https://github.com/codex-storage/codex-contracts-eth/issues/154
There is one question to be answered about what the node should do when it restarts (after an outage for example) and finds his slot to be in `Repair` state. For more see bellow.
=> feat: repair is rewarded

codex/sales.nim, codex/sales/slotqueue.nim, tests/codex/sales/testslotqueue.nim
- asyncSpawns `run` and worker `dispatch` in slotqueue.
- removes usage of `then` from slotqueue.
- Based on https://github.com/codex-storage/nim-codex/pull/1033
- This PR is part of a larger set of fixes to the codebase that removes usage of a faulty pattern of not awaiting or asyncSpawning futures.
=> fix(slotqueue): asyncSpawns futures correctly

codex/contracts/market.nim, codex/sales.nim, tests/codex/helpers/mockmarket.nim, tests/codex/sales/testsales.nim
- ensures `addSlotToQueue` does not raise exceptions as it is now asyncSpawned
- Based on https://github.com/codex-storage/nim-codex/pull/1033
- This PR is part of a larger set of fixes to the codebase that removes usage of a faulty pattern of not awaiting or asyncSpawning futures.
=> fix(sales): replaces `then` with `asyncSpawn`

.github/workflows/nim-matrix.yml
A quick PR which splits [Nim matrix](../../actions/workflows/nim-matrix.yml) workflow, to decrease its run duration by 20-30 minutes.
=> ci: split nim-matrix workflow

codex/node.nim, codex/utils/timer.nim
- prevents futures from silently failing
- also stops clock after the validator is stopped, which will help with graceful shutdowns
=> fix(codexnode): ensure timer loop is asyncSpawned

codex/blockexchange/engine/advertiser.nim, codex/blockexchange/engine/discovery.nim, codex/blockexchange/engine/engine.nim
- `asyncSpawn` futures (that raise []) in advertiser, discovery, and engine modules
- prevents failures in the futures from silently failing
- replaces `engine.blockexcTasks` with `TrackedFutures`, which tracks and cancels long-running futures
=> fix(blockexchange): ensures futures are asyncSpawned

tests/integration/codexprocess.nim, tests/integration/hardhatprocess.nim, tests/integration/nodeprocess.nim
- Ensures no exceptions are raised from `captureOutput`
- Asyncspawns the future to ensure errors are not silently swallowed
=> fix(nodeprocess): asyncspawn capture output

codex/blockexchange/engine/advertiser.nim, codex/blockexchange/engine/discovery.nim, codex/blockexchange/engine/engine.nim, codex/sales.nim, codex/sales/slotqueue.nim, codex/utils/asyncstatemachine.nim, codex/utils/trackedfutures.nim, tests/codex/utils/testtrackedfutures.nim, tests/integration/nodeprocess.nim
- cleans up all instances of `.track` to use the `module.trackedfutures.track(future)` procedure, for better readability
- removes the `track` override that is no longer used in the codebase
Note: based on https://github.com/codex-storage/nim-codex/pull/1045.
=> refactor(trackedfutures): remove return of future from tracked futures api

codex/conf.nim
"Unhide" log-format CLI flag. Generally this should be left on default value, but there are cases when overriding this is helpful (for example running in Interactive Docker gives you color output, even though maybe you do not want it etc.).
=> fix: unhide log-format cli flag

codex/blockexchange/engine/engine.nim, codex/blockexchange/peers/peerctxstore.nim, tests/codex/blockexchange/testpeerctxstore.nim, tests/integration/testsales.nim
In the current situation when we initiate a block request, we send a wantBlock to one peer (even if they don't have the block, so it will be ignored) and we send wantHave messages to others, which are then discarded.
This PR fixes two issues:
- We only send wantBlock messages to peers who have the block. We use the same pseudo-random method for selecting a peer if multiple peers have the block.
- We track all peerWants instead of only the wantBlocks. This is according to spec, and solves an issue in the case where a block is received/detected after the want-list message.
I did not want to solve both issues in the same PR. But test `NetworkStore - multiple nodes` in testblockexc.nim failed because of the second issue after I fixed the first one. So instead of having to "break" a correct …
=> Fix sending of WantBlocks messages and tracking of peerWants

flake.lock, flake.nix, nix/README.md, nix/default.nix, nix/service.nix
Added service definition for Nim Codex and tests.
The service can be instantiated by including it in flake inputs:
```nix
inputs = {
nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
codex-flake.url = "git+https://github.com/codex-storage/nim-codex?submodules=1#";
};
```
and configuring the service:
```nix
services.nim-codex = {
enable = true;
settings = {
data-dir = "/var/lib/codex-test";
};
};
```
=> Add nix service definition for codex

nix/README.md
Include the instructions for running nim-codex as a systemd service on NixOS.
=> nix: update readme

codex/contracts/market.nim, codex/contracts/marketplace.nim, tests/contracts/testContracts.nim
Implementation for https://github.com/codex-storage/codex-contracts-eth/pull/141
=> refactor: marketplace custom errors handling

codex/rest/api.nim
This PR adds `Content-Disposition` header, even if the filename does not exist in the metadata, to force the browser to download the file.
=> feat(rest): add default content-disposition header for stream download 

.github/workflows/ci.yml, .github/workflows/docker-reusable.yml, .github/workflows/nim-matrix.yml, .github/workflows/release.yml
GitHub just announced [Linux arm64 hosted runners now available for free in public repositories (Public Preview)](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/).
This is similar to https://github.com/codex-storage/github-actions/pull/1 and we would like to switch Codex arm builds to GitHub hosted runners.
| Runner                           | Architecture | CPU | Memory  |
| -------------------------------- | ------------ | --- | ------- |
| `ubuntu-22-04`                   | `x86_amd64`  | `4` | `16 GB` |
| `buildjet-8vcpu-ubuntu-2204-arm` | `arm64`      | `8` | `12 GB` |
| `ubuntu-22-04-arm`               | `arm64`      | `4` | `16 GB` |
First round of comparison shows the following, for [Docker - …
=> feat: switch to github arm runners

codex/sales/states/slotreserving.nim, tests/codex/sales/states/testslotreserving.nim
This PR replaces the previous message ""Reservation not allowed" to the custom error message "SlotReservations_ReservationNotAllowed".
=> chore(marketplace): use custom error message when reservation is not allowed

.gitignore, Jenkinsfile, flake.nix, nix/README.md, nix/checksums.nix, nix/csources.nix, nix/default.nix, nix/nimble.nix
Because of the recent bump of Nim compiler for codex to >2 version, using the system Nim provided by nixpkgs became unusable since the nim-codex couldn't build. Because of this I've adapted the derivation to be similar to the one of [nimbus-eth2](https://github.com/status-im/nimbus-eth2) where we build Nim compiler using nimbus-build-system.  
The pipeline on Jenkins is currently set to build nim-codex through flake, but there is a possibility to run the nix tests in the pipeline with slight modifications of the ci agents([the error](https://ci.status.im/job/nim-codex/job/systems/job/linux/job/x86_64/job/package/58/console) when running nix tests).
```shell
error: a 'x86_64-linux' with features {kvm, nixos-test} is required to build …
```
=> ci: create jenkins pipeline and enable build of nim compiler

codex/sales/slotqueue.nim, tests/codex/sales/testslotqueue.nim
When an item in the slotqueue is already seen, then a worker got popped from the list of workers, and was not added back again. This meant that the number of workers steadily declined as the queue was paused and unpaused.
possible fix for #1072
=> fix slotqueue worker starvation

codex/rest/api.nim, tests/integration/testrestapi.nim
I had to debug a download failure and ended up adding slightly better error feedback. Also noted some dead code, which I have removed.
=> Minor improvements to download API

docker/docker-entrypoint.sh
This is a quick and one more workaround for Docker images.
Now, we can pass `BOOTSTRAP_NODE_URL` and optionally `BOOTSTRAP_NODE_URL_WAIT` variables.
1. Entrypoint will loop for `BOOTSTRAP_NODE_URL_WAIT` or default for `300` seconds
2. Will try to get SPR from `BOOTSTRAP_NODE_URL/api/codex/v1/spr`
3. Will stop execution if SPR not received in time.
`BOOTSTRAP_NODE_URL` should be passed in form of base URL - `http://localhost:8080`.
=> docker: add BOOTSTRAP_NODE_URL to the Docker entrypoint

tests/examples.nim, tests/integration/codexclient.nim, tests/integration/marketplacesuite.nim, tests/integration/testmarketplace.nim, tests/integration/testproofs.nim, tests/integration/testrestapi.nim, tests/integration/testupdownload.nim, tests/integration/testvalidator.nim
When working on price-per-byte feature, I added two functions to `tests/integration/marketplacesuite.nim`:
```nim
proc slotSize(blocks: int): UInt256 =
(DefaultBlockSize * blocks.NBytes).Natural.u256
proc datasetSize(blocks, nodes, tolerance: int): UInt256 =
(nodes + tolerance).u256 * slotSize(blocks)
```
They are not correct, and should be defined as follows:
```nim
proc slotSize(blocks, nodes, tolerance: int): UInt256 =
let ecK = nodes - tolerance
let blocksRounded = roundUp(blocks, ecK)
let blocksPerSlot = divUp(blocksRounded, ecK)
(DefaultBlockSize * blocksPerSlot.NBytes).Natural.u256
proc datasetSize(blocks, nodes, tolerance: int): UInt256 =
return nodes.u256 * slotSize(blocks, nodes, tolerance)
```
The functions are used in the following integration tests:
- …
=> fix dataset and slot size calculations in integration tests

build.nims
Removes the `VERSION` rename to `VERSION_temp` in the Makefile, instead relying on a change in `nim-nat-traversal`.
The change in `nim-nat-traversal` uses `-iqoute` to include the `nim-nat-traversal/vendor/libnatpmp-upstream` directory in the search paths. `-iquote` will match the `vendor/libnatpmp-upstream/VERSION` file for `#include "version"` and not `#include <version>`, the latter being what is included by the macos sdk and was causing issues with `-I`. The [gcc 14.2 docs](https://gcc.gnu.org/onlinedocs/gcc-14.2.0/cpp/Invocation.html#index-I) describe how `-iquote` alleviates this issue:
> Directories specified with -iquote apply only to the quote form of the directive, #include "file". Directories specified with -I, -isystem, or -idirafter apply to lookup for both the #include …
=> fix(build): compilation on macos when including nim-nat-traversal

codex/blockexchange/engine/engine.nim
While working on https://github.com/codex-storage/nim-codex/pull/1106 I was hit with a linting problem in `codex/blockexchange/engine/engine.nim` (#1106 fails with [linting error](https://github.com/codex-storage/nim-codex/actions/runs/13236294382/job/36941754410?pr=1106)).
Looks like the change was introduced by @dryajov, so maybe there is something going on with his npx configuration? Or maybe there is some point being made? I still do not understand how did it get through to the master - it is failing my builds how did it not fail before 🧐?
Because, others may be dealing with the same problem, this is a separate PR that just fixed this small linting error.
=> fix linting in "codex/blockexchange/engine/engine.nim"

.github/workflows/docs.yml
Currently the API docs are being published on every PR and every push to the master. This results in out of sync API spec, which should only be updated when there is a release.
In this PR, I am deploying the OpenAPI spec only when tagged with a tag matching `v*.*.*`.
> There is a linting problem on master that will prevent this PR from being merged. It is addressed in #1107 to make it visible (I still do not get how it is even possible). Thus once #1107 is merged, I will rebase this one.
=> upload OpenAPI artifacts and publish docs only when tagged

.github/workflows/docker-reusable.yml
We recently observed that `amd64` Docker builds, which uses `ubuntu-22.04` runner, started to fail because they are running on the self-hosted runners.
And there two issues with that
- Self hosted runners are not configured properly to run Docker
- We have clashed labels - `ubuntu-22.04` is used by self-hosted runners and GitHub ones as well
PR contains a quick workaround to switch to the GutHub hosted runners with the labels `ubuntu-24.04` and `ubuntu-24.04-arm`.
=> fix: use ubuntu-24.04 runners for docker workflows

codex/codex.nim, codex/conf.nim, codex/erasure/backend.nim, codex/erasure/backends/leopard.nim, codex/erasure/erasure.nim, codex/node.nim, codex/utils/arrayutils.nim, tests/codex/node/helpers.nim, tests/codex/node/testcontracts.nim, tests/codex/node/testnode.nim, tests/codex/testerasure.nim
This PR introduces the following changes:
- Utilizes `TaskPool` to spawn separate threads for the erasure encoding and decoding.
- Adds a new `num-threads` flag, enabling users to specify the number of CPU threads available for TaskPool workers.
**Docs [PR](https://github.com/codex-storage/codex-docs/pull/58)**
=> feat: multithreading support for erasure coding

codex/stores/repostore/operations.nim, codex/stores/repostore/store.nim, tests/codex/examples.nim, tests/codex/stores/testrepostore.nim
Fixes #1108
This PR:
* fixes the broken deletes for non-orphan blocks (i.e., blocks that are part of a dataset);
* makes `deleteBlock` more strict by actually returning an error on illegal deletes instead of failing silently;
* adds additional tests to cover the peculiar aspects of deletes for non-orphan blocks.
=> Fix/repostore deletes for non-orphan blocks

codex/codex.nim, codex/conf.nim, codex/contracts/config.nim, codex/contracts/market.nim, tests/contracts/testMarket.nim
=> chore(marketplace): add a cache for storage requests

codex/manifest/manifest.nim, codex/streams/storestream.nim, tests/codex/blockexchange/discovery/testdiscovery.nim
This PR remove the warning `Warning: use treeCid instead; cid is deprecated` by removing the `cid` function from the manifest.
=> chore: Remove deprecated cid function

codex/contracts/provider.nim, tests/contracts/helpers/mockprovider.nim, tests/contracts/testDeployment.nim
Ethers was swallowing canellations and turning them into EthersErrors, which was causing the sales statemachine to error when it should have been simply cancelling the current state's run. Hopefully fixes the intermittently failing marketplace integration test.
Note: this PR is based off of https://github.com/codex-storage/nim-ethers/pull/105, let's get that merged first so we can move our Ethers dependency off a branch.
=> chore(deps): bump ethers to propagate cancellations

codex/erasure/backends/leopard.nim, codex/errors.nim, codex/rest/coders.nim, codex/utils/asyncheapqueue.nim, codex/utils/natutils.nim, tests/codex/stores/testqueryiterhelper.nim, tests/codex/testasyncheapqueue.nim, tests/codex/testnat.nim
This PR update the imports of `results` to remove the deprecation warning.
=> chore: use results instead of stew/results

tests/integration/codexconfig.nim, tests/integration/multinodes.nim, tests/integration/testblockexpiration.nim
Moves `testblockexpiration` from an `ethersuite` to a `multinodesuite`, simplifying the test quite a lot.
=> chore(integration): simplify block expiration integration test

openapi.yaml
Deser fails with "missing field 'error'" in the case of no error.
=> Missing nullability causes json-serialize failure

.github/actions/nimbus-build-system/action.yml, .github/workflows/nim-matrix.yml
The CI take input as string not as boolean using `true` or `false`. This PR fixes this when enabling gcc 14 on linux.
=> fix(ci): handle coverage as a string to enable gcc 14 on linux

codex/sales.nim, codex/sales/reservations.nim, tests/codex/sales/testreservations.nim
Currently, when an availability is updated, `sales` is notified only when the freeSize increases.
This PR changes this behavior to notify `sales` when freeSize, duration, minPricePerBytePerSecond, or totalCollateral is increased. All those parameters are taken into consideration when trying to find an availability matching the slot.
=> chore(marketplace): notify sales when duration, minPricePerBytePerSecond or totalCollateral is updated

codex/contracts/market.nim
NOTE: Dependent upon https://github.com/codex-storage/nim-ethers/pull/109
=> fix: ethers no longer leaks AsyncLockError

codex/discovery.nim
We receive a log file from a user whose node doesn't work. We don't know the annouce addresses because it runs with INFO level by default. This change will help us assist users in the future.
=> Trace to Info for DHT/announce record updates

codex/rest/api.nim, tests/integration/codexclient.nim, tests/integration/codexprocess.nim, tests/integration/marketplacesuite.nim, tests/integration/multinodes.nim, tests/integration/testblockexpiration.nim, tests/integration/testecbug.nim, tests/integration/testmarketplace.nim, tests/integration/testproofs.nim, tests/integration/testpurchasing.nim, tests/integration/testrestapi.nim, tests/integration/testsales.nim, tests/integration/testupdownload.nim, tests/integration/testvalidator.nim, tests/testTaiko.nim
This PR replaces the standard Nim client with the chronos http client for all integration tests. The trigger for this was us realizing that the blocking client will choke the (chronos) output processor and cause tests to freeze because it starves it.
As an easter egg, and because the chronos client is a lot less lenient with header screw-ups, this PR also:
Fixes #1163
=> feat(integration): use async client instead of standard Nim HTTP client

codex/contracts/market.nim, codex/market.nim, codex/sales/states/cancelled.nim, codex/sales/states/failed.nim, tests/codex/helpers/mockmarket.nim, tests/codex/sales/states/testcancelled.nim
=> fix(marketplace): catch Marketplace_SlotIsFree and continue the cancelled process

tests/codex/helpers/randomchunker.nim
In our tests we usually use the `RandomChunker` as follows:
```nim
proc makeRandomBlocks*(
datasetSize: int, blockSize: NBytes
): Future[seq[Block]] {.async.} =
var chunker =
RandomChunker.new(Rng.instance(), size = datasetSize, chunkSize = blockSize)
while true:
let chunk = await chunker.getBytes()
if chunk.len <= 0:
break
result.add(Block.new(chunk).tryGet())
```
Thus, we are effectively creating `RandomChunker` with `pad = false`.
But then, in `await chunker.getBytes()` we have the following:
```nim
proc getBytes*(c: Chunker): Future[seq[byte]] {.async.} =
##
var buff = newSeq[byte](c.chunkSize.int)
let read = await c.reader(cast[ChunkBuffer](addr buff[0]), buff.len)
if read <= 0:
return @[]
c.offset += read
if not c.pad and buff.len > read:
buff.setLen(read)
return move buff
```
The …
=> fixes RandomChunker not respecting padding

codex/merkletree/codex/codex.nim
Based on the latest [benchmarks](https://github.com/codex-storage/nim-codex/issues/1162), Constantine SHA256 demonstrates excellent performance for hashing 32-byte payloads. This PR updates the CodexTree hashing algorithm by replacing mhash 256 with Constantine SHA256.
=> deps: use constantine sha256 for codex tree hashing

openapi.yaml
The contract's [perf optimization PR](https://github.com/codex-storage/nim-codex/pull/1094) changed some API types from string to integer without documenting them, so I am mainly adding these.
=> chore: adding perf optimization tweaks to openapi

.github/actions/nimbus-build-system/action.yml, .github/workflows/ci.yml, .github/workflows/release.yml, Makefile, build.nims
This PR closes #1141
- We've switched to `ubuntu-latest` (`24.04`) for coverage because 20.04 will be fully unsupported by 2025-04-15
- To fix the issue with the `lcov` v2 (which is a default on ubuntu-24.04) it was required to pass [`--keep-going`](https://man.archlinux.org/man/lcov.1.en) and use default GCC 13 (GCC 14 compatibility issue need to be solved, but let's do it later)
> Do not stop if error occurs: attempt to generate a result, however flawed.
- Release workflow was switched to `ubuntu-22.04`
- GCC-14 is not easy available on Ubuntu < 24.04 - so, install and use it only on the new versions
And to fix CI, it was required to update submodule [nim-leveldbstatic to 0.2.1](https://github.com/codex-storage/nim-leveldb/pull/4).
=> ci: switch out from ubuntu 20.04

openapi.yaml
While working on [generating the typescript types from the openapi yaml file](https://github.com/codex-storage/codex-js/blob/4750e0b6fe9430cef3d85b15bbddd937f454cbb8/src/openapi.ts#L348), I noticed that the required parameter was missing for several definitions. 
This PR add those required parameters and fix few minor mistakes.
=> chore(openapi): add required parameters

openapi.yaml, redocly.yaml
This PR includes: 
1- Adding the mssing `collateralPerByte` to `StorageAsk`
2- Fix request's state enum value `error` to `errored`
3- Enforce the rule `no-required-schema-properties-undefined` to make sure that required properties are present in the definition 
4- Add a `422` error for `/data` (upload) when the filename or the mimetype is invalid
5- Disable the rule `no-server-example.com` because `localhost` makes sense for us
=> chore(openapi): fix issues 

codex/contracts/config.nim, codex/contracts/market.nim, codex/contracts/proofs.nim, codex/contracts/requests.nim
Adds 10% to gas estimates for `reserveSlot`, `fillSlot`, `freeSlot` and `markProofAsMissing`.
These calls could otherwise run out of gas because the on-chain state may have changed
between the time of the estimate and the time of processing the transaction.
Depends on a change in nim-ethers: https://github.com/codex-storage/nim-ethers/pull/115
Fixes #1133
=> Increase gas estimates

.github/workflows/docker-reusable.yml, .github/workflows/docker.yml
Adds another job to Docker building, that creates Contract's image that is compatible with the image being built, then this image is linked using Docker image labels. This is in order to support https://github.com/codex-storage/codex-factory
=> ci: add compatible contracts image for nim-codex docker image

codex/sales/reservations.nim
We use `marketplace` everywhere related to Marketplace, but it is missing in the `reservations` module.
=> chore: add marketplace topic to reservations

tests/contracts/testMarket.nim
Bump contracts to master branch.
There was a change that allowed hardhat to have multiple blocks with the same timestamp, so this needed to be reflected in two tests.
=> chore: bump contracts to master

Makefile, tests/contracts/testClock.nim, tests/ethertest.nim, tests/helpers.nim, tests/integration/multinodes.nim, tests/tools/cirdl/testcirdl.nim
Linea is supporting only Websocket. 
So it would be better to use it in our testing. 
Depends on https://github.com/codex-storage/nim-ethers/pull/112.
=> chore(marketplace): switch to websocket

tests/contracts/testMarket.nim, tests/integration/codexclient.nim, tests/integration/testrestapivalidation.nim
Fixes an intermittent problem with other tests because the api validation test kept a codex node alive after it finishes.
Also includes a fix for an unrelated flaky market test, to make the CI pass.
=> fix(integration): fix api validation test

codex/sales.nim, codex/sales/reservations.nim, codex/sales/salesagent.nim, codex/sales/states/preparing.nim, codex/utils/asyncstatemachine.nim, tests/codex/helpers/mockreservations.nim, tests/codex/sales/states/testcancelled.nim, tests/codex/sales/states/testerrored.nim, tests/codex/sales/states/testfinished.nim, tests/codex/sales/states/testignored.nim, tests/integration/codexclient.nim, tests/integration/testmarketplace.nim
When an SP was processing a slot and the sale was ignored, the cleanup function was blocked, preventing workers from picking up new items from the slot queue.
This PR should fix that and maybe #1210.
=> fix: sales cleanup cancellation

codex/contracts/market.nim
This PR bumps contracts needed for the following PRs: 
- https://github.com/codex-storage/nim-codex/pull/1235
- https://github.com/codex-storage/nim-codex/pull/1188
- https://github.com/codex-storage/nim-codex/pull/1160
It includes a fix for token allowance extracted from [vault PR](https://github.com/codex-storage/nim-codex/pull/1196/commits/9b9d0b23fe16e3746eee098bc95b90d3640249c4)
=> chore: bump contracts

codex/sales/reservations.nim, tests/codex/sales/testreservations.nim, tests/contracts/testMarket.nim, tests/integration/testmarketplace.nim
This PR uses `totalRemainingCollateral` instead of `totalCollateral` when trying to detect availability changes for notifying the sales module during the availability update. 
The  `totalRemainingCollateral`  has to be used because this is the value updated when a reservation is created or deleted. 
The `totalCollateral` is the initial value used when creating / updating the availability from the JSON api.
=> fix(availabilities): use totalRemainingCollateral instead of totalCollateral for comparaison 

codex/sales/statemachine.nim, codex/sales/states/preparing.nim, codex/sales/states/unknown.nim, tests/codex/sales/states/testpreparing.nim, tests/codex/sales/states/testunknown.nim
=> fix(sales): do not crash when retrieving request fails

codex/purchasing/states/submitted.nim
=> fix(purchasing): fix crash completing future more than once

tests/contracts/testMarket.nim
Fetching past contract events test was failing with fetched contract events out of order. Advancing the time increasing the timestamp of the next automined block, allowing the events to occur in different blocks but with the same timestamp.
=> fix(tests): fetching past contract events test

codex/codex.nim, codex/conf.nim, codex/contracts/config.nim
This PR adds a new command line argument to configure the maxPriorityFeePerGas available now with [EIP-1559 implementation] (https://github.com/codex-storage/nim-ethers/pull/113)
=> feat(marketplace) - add command line arg for maxPriorityFeePerGas

codex/codex.nim, codex/contracts/deployment.nim, tests/contracts/testDeployment.nim, tools/cirdl/cirdl.nim
Closes #987 
I know it is bit hacky having the `CodexConf` object here, but I did not really want to refactor the `Deployment` module to move this part out so went about it like this.
=> feat(cirdl): auto-discovery of marketplace contract

codex/node.nim, codex/sales.nim, codex/sales/salesagent.nim, codex/sales/salescontext.nim, codex/sales/salesdata.nim, codex/sales/slotqueue.nim, codex/sales/states/downloading.nim, tests/codex/helpers/mockmarket.nim, tests/codex/node/testcontracts.nim, tests/codex/sales/testsales.nim, tests/codex/sales/testslotqueue.nim, tests/codex/testpurchasing.nim, tests/codex/testvalidation.nim
Previously we used request.expiry as the block expiry, but the former is a duration in seconds, whereas the latter is a timestamp.
- Slot queue items can now either contain an expiry (when they represent a newly created request) or not contain an expiry (when they represent a recently freed slot that need repairing)
- Slot queue items are now added to the sales agent state, so that they can be re-added easily, instead of having to recreate the slot queue item from on-chain state.
Extracted the fix from #1196
=> fix(sales): fix marketplace block expiry

codex/contracts/market.nim
Found in #750. 
[Some transactions](https://explorer.testnet.codex.storage/tx/0x82e413f06ac71885fc0239e196f2ab560523c2e826d7e8d0abf23793aef70bba) failed on testnet with gas usage = gas limit and the error displayed in the explorer is "out of gas".
=> chore: increase gas limits

tests/codex/stores/repostore/testcoders.nim, tests/codex/stores/testkeyutils.nim, tests/imports.nim, tests/testCodex.nim, tests/testContracts.nim, tests/testIntegration.nim, tests/testTools.nim
Imports all files that are named `test*.nim` automatically, so we cannot forget to add them.
Includes compilation fixes for tests that were forgotten, and were therefore not run in the CI before.
=> fix(tests): auto import all tests files and fix forgotten tests
