codex-storage/nim-codex

- ipfs/dht/routing.nim
- tests/ipfs/testDhtRouting.nim
> Fix: adapt to latest libp2p api

- .github/workflows/ci.yml
- dagger.nimble
- dagger/blockexchange/network.nim
- dagger/stores/blockexchange.nim
- nim.cfg
- tests/dagger/blockexc/testengine.nim
- tests/dagger/blockexc/testnetwork.nim
- tests/dagger/examples.nim
Fixes several compilation issues with latest libp2p as well as bumps the nim compiler requirement to 1.4.6.
> fix compilation issues with latest libp2p

- .github/workflows/ci.yml
- .gitignore
- .gitmodules
- Makefile
- config.nims
- dagger.nimble
Moving dagger to nimbus build system to allow for better dependencies control.
> Build system

- dagger/rest/api.nim
Downloading a CID that is unknown to the network would wait for the blockexchange to try to get the data. However, a subsequent API call, eg upload for that CID, or a blockexchange timeout would cause the dagger node to crash, due to an attempt to complete a future that had already been completed:
```shell
Error: unhandled exception: An attempt was made to complete a Future more than once. Details:
Future ID: 439
Creation location:
route.nim(339)    restApiDaggerV1DownloadIdGetHandler
First completion location:
api.nim(118)    [unspecified]
Second completion location:
asyncfutures2.nim(384)    [unspecified]
```
We were able to narrow this down to an attempt to call  `resp.finish()` when the download block had already returned an `RestApiResponse` (and never sent any chunks to the response …
> fix(rest): download unknown cid

- dagger/rest/api.nim
This PR achieves the following:
1. Improves the exception handling when dialling a peer fails or an unknown error occurs.
2. Add a `Content-Type` header to the `/download` endpoint of `application/octet-stream`, which is [defined by MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#types) as meant to be used for "generic binary data (or binary data whose true type is unknown)". 
Co-authored-by: Michael Bradley <michaelsbradleyjr@gmail.com>
> [rest api]: improve exception handling for `/connect` and add `content-type` header for `/download`

- dagger/manifest/manifest.nim
- dagger/node.nim
- dagger/stores/cachestore.nim
- dagger/storestream.nim
- tests/dagger/testasyncheapqueue.nim
- tests/dagger/testmanifest.nim
- tests/dagger/testnode.nim
- tests/dagger/teststorestream.nim
- tests/testAll.nim
Adding a stream abstraction around stores, to be used with the PoR proofs.
> Store stream

- dagger/blocktype.nim
- dagger/chunker.nim
- dagger/manifest/coders.nim
- dagger/node.nim
- dagger/rest/api.nim
- dagger/streams/storestream.nim
- tests/dagger/testchunking.nim
- tests/dagger/testnode.nim
- tests/dagger/teststorestream.nim
Use StoreStream, which guarantees ordered download
> Node storestream

- .github/workflows/ci.yml
See: https://github.com/status-im/nimbus-build-system#nim_commit
> Test with multiple Nim versions in GitHub Actions

- dagger.nimble
- dagger/contracts.nim
- dagger/contracts/market.nim
- dagger/contracts/offers.nim
- dagger/contracts/requests.nim
- dagger/contracts/storage.nim
- dagger/market.nim
- dagger/purchasing.nim
- tests/contracts/examples.nim
- tests/contracts/testMarket.nim
- tests/dagger/examples.nim
- tests/dagger/helpers/mockmarket.nim
- tests/dagger/testpurchasing.nim
- tests/examples.nim
- tests/testContracts.nim
- tests/testDagger.nim
Adds a simple purchasing algorithm that submits a request for storage, and selects a storage offer.
- Introduces `Purchasing` class that performs all actions for buying storage
- Introduces `Market` abstraction around the smart contracts, so that they can be mocked out in tests
> Purchasing

- dagger.nim
- dagger/dagger.nim
- dagger/erasure/erasure.nim
- dagger/manifest.nim
- dagger/manifest/coders.nim
- dagger/manifest/manifest.nim
- dagger/manifest/types.nim
- dagger/node.nim
- dagger/rest/api.nim
- tests/dagger/testnode.nim
> Integrate erasure

- config.nims
- dagger.nim
- dagger/conf.nim
> Propper logging options

- .gitignore
- config.nims
- dagger.nimble
- nimble.lock
- tests/nim.cfg
- tests/testContracts.nim.cfg
- tests/testDagger.nim.cfg
The workflow based on Nimble lock files will be documented soon in the https://github.com/status-im/nim-workspace repo. For now, I plan to merge this as a helpful step for testing the new [Nim language server](https://github.com/nim-lang/langserver) in the repo .
> Nimble lock file

- .github/workflows/ci.yml
- config.nims
- dagger.nim
- dagger/blockexchange/engine.nim
- dagger/conf.nim
- dagger/node.nim
> Dev-ops stuff

- codex/stores/blockstore.nim
- codex/stores/cachestore.nim
- codex/stores/fsstore.nim
- codex/stores/networkstore.nim
- tests/codex/stores/testcachestore.nim
- tests/codex/stores/testfsstore.nim
- tests/codex/testerasure.nim
> WIP: Harmonize BlockStore API

- codex.nimble
- nimble.lock
- I have performed synchronization using `add-all-vendor-projects` and `nimble
lock` in `nim-workspaces` project
- I am still unable to build the project using `nimble codex` but this is caused
by the fact that it seems like there is `questionable`/1.6 Nim macro expansion
issues (I will report separate issue).
> Sync submodule dependencies and lock file

- codex/node.nim
- tests/codex/testnode.nim
Integrate block fetching with contracts
> Contract store

- codex/stores/sqlitestore.nim
I was reviewing some notes from my discussion last week with @dryajov and noted his observation that `SQLiteStore` seemed about 2x slower for reads compared to `FSStore`. On Friday I spent some time with nim-datastore re: https://github.com/status-im/questionable/issues/19, so it was fresh in my mind. I realized something that is probably impacting the read performance of `SQLiteStore` (cf. #160), which wraps nim-datastore's `SQLiteDatastore`.
nim-datastore's [`iterator query`](https://github.com/status-im/nim-datastore/blob/master/datastore/sqlite_datastore.nim#L352) for `SQLiteDatastore`  yields a `(key, data)` tuple, i.e. both the `id` and `data` columns are read for each matching row.
However, `method listBlocks` only needs each `Cid`, i.e. it only needs to read from the `id` column …
> custom query for listBlocks

- BUILDING.md
- README.md
Closes #216.
---
TODO: verify all instructions work for
In future PRs we can make any number of improvements, but this is a solid starting point.
I hope to provide instructions re: getting setup with MSYS2 in a headless Windows container, but I need to spend more time with the [resource](https://github.com/StefanScherer/windows-docker-machine) suggested by dryajov.
> add BUILDING.md and link from root README.md

- .gitmodules
- codex.nimble
Support latest version of nim-ethers which relies on nim-eth.
NOTE: This commit points to PR #31 which is a branch of nim-ethers. That branch should probably be merged first, and this PR updated to point to the commit on main.
> bump nim-ethers to 0.2.2, add nim-eth dependency

- codex.nimble
Includes a fix for Nil exception on unthandled exception
> [build] Update asynctest to version 0.3.2

- codex/blockexchange/network/networkpeer.nim
- codex/blockexchange/protobuf/blockexc.nim
- codex/blockexchange/protobuf/message.nim
- codex/blockexchange/protobuf/message.proto
- tests/codex/blockexchange/testnetwork.nim
> Replace protobuf serialization for Block exchange with minprotobuf

- codex/codex.nim
- codex/conf.nim
- codex/discovery.nim
- tests/codex/helpers/nodeutils.nim
- tests/codex/storageproofs/testnetwork.nim
- tests/codex/testnode.nim
> Rework discovery

- .gitignore
- codex.nim
- codex/blockexchange/engine/engine.nim
- codex/blockexchange/network/networkpeer.nim
- codex/discovery.nim
- codex/erasure/erasure.nim
- codex/manifest/manifest.nim
- codex/node.nim
- codex/rest/api.nim
- codex/rng.nim
- codex/storageproofs/stpnetwork.nim
- codex/stores/cachestore.nim
- codex/stores/fsstore.nim
- codex/stores/networkstore.nim
- codex/streams/asyncstreamwrapper.nim
- codex/streams/storestream.nim
- tests/codex/blockexchange/engine/testblockexc.nim
- tests/codex/blockexchange/testnetwork.nim
- tests/codex/helpers.nim
The goal of this PR is to have nim-codex start tracking nim-libp2p's `unstable` branch.
To make that work, a few other dependencies need to be bumped.
It's also necessary to make some changes to nim-libp2p-dht so that it works with nim-libp2p's `unstable` branch and latest nim-bearssl. See https://github.com/status-im/nim-libp2p-dht/pull/47.
The changes to nim-libp2p-dht were successful: all tests passing for https://github.com/status-im/nim-libp2p-dht/pull/47.
~However, in nim-codex the result is mixed at time of writing:~
~* `make exec` compiles successfully and `build/codex` seems to work as expected.~
~* `task testIntegration` compiles successfully and all tests pass.~
~* `task testContracts` compiles successfully and all tests pass.~
~* `task textCodex` (in `make test` and `make …
> track latest nim-libp2p's master branch

- codex/utils/fileutils.nim
- codex/utils/keyutils.nim
- tests/codex/testutils.nim
- tests/codex/utils/testkeyutils.nim
Unix permissions don't work on Windows; added check for ACL on windows.
> Fixes loading of private key on Windows

- codex/rest/api.nim
- codex/rest/coders.nim
- tests/testIntegration.nim
Note, this puts `/info` and `/loglevel` under `/debug`.
> Log topic filtering

- codex/blockexchange/engine/pendingblocks.nim
- tests/codex/blockexchange/testpendingblocks.nim
- tests/codex/testblockexchange.nim
Avoid leaking blocks and add `inFlight` flag. 
Plus test for pending blocks.
> Blocks leak and inflight for pending blocks

- codex.nimble
Reduces the time required to build nim-leopard.
> [build] Update nim-leopard to version 0.1.0

- .github/workflows/Readme.md
Lessons learned from speeding up the CI in
https://github.com/status-im/nim-codex/pull/303
> [ci] Add tips for maintaining CI

- codex/node.nim
Thanks for noticing that this was missing @AuHau!
> [node] fix: stop validator

- tests/codex/testvalidation.nim
Test could fail when it was started right at the
boundary of a period (on the system clock)
> [validator] fix intermittent test failure

- README.md
- codex.nim
- codex/conf.nim
This PR widens the configuration repertoire of Codex by adding support for env. variables and configuration files.
Maybe in future, we could extend the configuration-file part by having default configuration file paths (something like `~/.codex.toml`), but I left this part out for now.
> feat: adding config and env. variable support

- codex/codex.nim
- codex/conf.nim
- codex/contracts.nim
- codex/contracts/deployment.nim
- tests/contracts/deployment.nim
- tests/contracts/testContracts.nim
- tests/contracts/testDeployment.nim
- tests/contracts/testMarket.nim
- tests/integration/testproofs.nim
Closes #372 
Needs https://github.com/status-im/codex-contracts-eth/pull/54 to be merged first.
> feat: contract address management

- codex/rest/api.nim
> fix(api): set content type for json

- codex/codex.nim
- codex/contracts/market.nim
- codex/node.nim
- codex/proving.nim
- codex/rest/api.nim
- codex/rest/json.nim
- codex/sales.nim
- openapi.yaml
- tests/integration/codexclient.nim
> feat: slots rest api

- codex/rest/coders.nim
- codex/rest/json.nim
- codex/utils/stintutils.nim
- openapi.yaml
- tests/contracts/deployment.nim
- tests/contracts/time.nim
- tests/integration/codexclient.nim
- tests/integration/testIntegration.nim
> feat: bigint uses decimal over hex encoding

- .github/ISSUE_TEMPLATE/feature_request.md
It may be useful to have a Feature request template for easier requests.
I've added a default one GitHub proposed.
> Add Feature request template

- .gitignore
- codex/blockexchange/network/network.nim
- codex/blockexchange/network/networkpeer.nim
- codex/blockexchange/protobuf/message.nim
> Fix for decoding large manifests

- codex/stores/blockstore.nim
- codex/stores/cachestore.nim
- codex/stores/networkstore.nim
- codex/stores/repostore.nim
- tests/codex/stores/testrepostore.nim
This is the first part of the work on https://github.com/codex-storage/nim-codex/issues/436
> feat: ensure block expiry

- codex/utils/json.nim
- tests/codex/utils/testjson.nim
> Fix json serialization for cid and enums

- docs/TWOCLIENTTEST.md
> docs: update api for two client test

- codex/erasure/backend.nim
- codex/erasure/erasure.nim
- codex/manifest/coders.nim
- codex/manifest/manifest.nim
- tests/codex/slots/provingtestenv.nim
- tests/codex/slots/testslotbuilder.nim
- tests/codex/testerasure.nim
- tests/codex/testmanifest.nim
Add indexing strategy to manifest and propagate to erasure
> cleanup manifest and wire in strategy

- codex/blocktype.nim
- codex/manifest/manifest.nim
- codex/streams/storestream.nim
- tests/codex/slots/testslotbuilder.nim
> Block and manifest as objects

- codex/node.nim
- codex/slots/builder/builder.nim
- tests/codex/node/testcontracts.nim
- tests/codex/slots/testslotbuilder.nim
Use correct slot block count
split out from #702
> Use correct slot block count

- codex/codex.nim
- codex/node.nim
- tests/codex/node/helpers.nim
- tests/codex/node/testcontracts.nim
- tests/codex/node/testnode.nim
- tests/integration/testproofs.nim
> Node use correct stores

- codex/blockexchange/engine/engine.nim
- codex/blockexchange/engine/pendingblocks.nim
- codex/erasure/backends/leopard.nim
- codex/erasure/erasure.nim
- codex/logutils.nim
- codex/node.nim
- codex/sales/reservations.nim
- codex/sales/states/initialproving.nim
- codex/stores/blockstore.nim
- codex/stores/networkstore.nim
- codex/utils/poseidon2digest.nim
- config.nims
- tests/circuits/fixtures/proof_main.circom
- tests/codex/blockexchange/engine/testblockexc.nim
- tests/codex/helpers.nim
- tests/codex/helpers/mockmarket.nim
- tests/codex/node/helpers.nim
- tests/codex/node/testnode.nim
- tests/codex/sales/helpers/periods.nim
- tests/codex/sales/states/testinitialproving.nim
- tests/codex/sales/testsales.nim
- tests/integration/nodes.nim
- tests/integration/testIntegration.nim
Produces real ZK proofs when asked to do so by the sales module.
Extracted from #702 
Depends on #735
> Wire up prover

- codex/contracts/deployment.nim
- codex/sales/states/provingsimulated.nim
- tests/integration/marketplacesuite.nim
- tests/integration/multinodes.nim
- tests/integration/testproofs.nim
Uses the real Groth16 verifier in the smart contracts for the integration tests.
Extracted from #702 
Depends on #736
> Use real verifier

- .gitmodules
Updates libp2p to its new repo, as prescribed in #740
> Update repo for libp2p

- codex/rest/api.nim
- codex/rest/json.nim
- openapi.yaml
- tests/integration/codexclient.nim
- tests/integration/testIntegration.nim
Some details of the API calls don't line up with the openAPI spec.
This PR fixes some issues by changing the spec,
and a fixes others by changing the code.
> Openapi mismatches

- tests/integration/twonodes.nim
Also see https://github.com/codex-storage/codex-contracts-eth/pull/97
> chore(tests): Use circuit artifacts in codex circuit fixtures for tests

- codex/blockexchange/engine/discovery.nim
- codex/blockexchange/engine/engine.nim
- codex/blockexchange/engine/pendingblocks.nim
- codex/blockexchange/network/network.nim
- codex/discovery.nim
- codex/node.nim
- codex/stores/networkstore.nim
- codex/stores/repostore.nim
For the upload control flow:
Removes traces where they contribute little to nothing.
Turns traces into infos/warns where appropriate.
> Reduce logging during file upload

- codex/contracts/market.nim
- codex/contracts/marketplace.nim
- codex/market.nim
- codex/purchasing.nim
- codex/purchasing/states/submitted.nim
- codex/rest/api.nim
- codex/sales/salesagent.nim
- openapi.yaml
- tests/codex/helpers/mockmarket.nim
- tests/codex/sales/testsales.nim
- tests/codex/sales/testsalesagent.nim
- tests/codex/testpurchasing.nim
- tests/contracts/testContracts.nim
- tests/contracts/testMarket.nim
- tests/examples.nim
- tests/integration/codexclient.nim
- tests/integration/marketplacesuite.nim
- tests/integration/testIntegration.nim
> feat: expiry specified with number of seconds

- codex/blockexchange/engine/discovery.nim
- codex/blockexchange/engine/engine.nim
- codex/blockexchange/engine/pendingblocks.nim
- codex/blockexchange/network/network.nim
- codex/blockexchange/network/networkpeer.nim
- codex/blockexchange/peers/peercontext.nim
- codex/blockexchange/peers/peerctxstore.nim
- codex/blockexchange/protobuf/message.nim
- codex/discovery.nim
- codex/rest/api.nim
- codex/stores/networkstore.nim
- codex/stores/repostore.nim
- codex/streams/storestream.nim
Same as https://github.com/codex-storage/nim-codex/pull/792
except for download flow.
> Update logging for download

- codex/validation.nim
> Inlines copying of hashset in validation.nim

- README.md
- docs/Marketplace.md
- docs/TwoClientTest.md
This PR adds a first version of a guide for running Codex with a local Geth network and buying/selling storage in the Marketplace.
> Updates tutorial with entry on how to run Codex with its Markeplace

- codex/sales/reservations.nim
- codex/sales/states/preparing.nim
- tests/codex/helpers/mockreservations.nim
- tests/codex/sales/states/testpreparing.nim
- tests/codex/sales/testreservations.nim
- tests/codex/sales/teststates.nim
Supersedes https://github.com/codex-storage/nim-codex/pull/816/
> fix: createReservation lock

- codex/erasure/asyncbackend.nim
- tests/codex/testerasure.nim
This disables scheduling erasure-coding on another thread. More details in an issue #854
> Temporarily disable threading in erasure coding

- codex/rest/api.nim
This PR add CORS support for POST and PATCH availability requests.
> Support CORS preflight requests for availability

- docs/Marketplace.md
Marketplace tutorial doc got a bit outdated. This (Draft) PR is work in progress to update the tutorial.
> updates Marketplace tutorial documentation

- codex/blockexchange/network/network.nim
> Fix: null-ref in networkPeer

- openapi.yaml
> docs: openapi node fix

- codex/rest/api.nim
- openapi.yaml
- tests/integration/codexclient.nim
- tests/integration/testblockexpiration.nim
- tests/integration/testupdownload.nim
- Download stream moved to `/data/CID/network/stream`
- Start download without stream: `/data/CID/network`
- Download only manifest: `/data/CID/network/manifest`
Updated openAPI.yaml and added tests.
> Download API upgrade

- codex/contracts/deployment.nim
As a part of the new Codex release we deployed new Marketplace contract.
Part of https://github.com/codex-storage/infra-codex/issues/248.
Related to https://github.com/codex-storage/codex-contracts-eth/pull/197.
> chore: new marketplace address for testnet

- .github/workflows/docs.yml
This is a quick PR to add Postman Collection which will be available on the following URL - [api.codex.storage/postman.json](https://api.codex.storage/postman.json).
We also will add a link to it in the documentation - [Codex API](https://docs.codex.storage/developers/api).
And some cosmetic changes
- Remove unnecessary quotes
- Default shell on Ubuntu is `bash`
> Build Postman Collection

- codex/contracts/market.nim
- codex/contracts/marketplace.nim
- codex/node.nim
- codex/utils/asyncstatemachine.nim
- tests/codex/utils/testasyncstatemachine.nim
- tests/contracts/testContracts.nim
- tests/contracts/testDeployment.nim
- tests/contracts/testMarket.nim
- tests/contracts/time.nim
- tests/integration/marketplacesuite.nim
- tests/tools/cirdl/testcirdl.nim
- tools/cirdl/cirdl.nim
This fixes the nonce issue that has been plaguing the testnet, causing banked up pending transactions and preventing requests from starting.
Bumps the following dependencies:
- nim-ethers to commit 6523e70eafecc3b9728a491058818e685bd384fb which contains a pinned nim-eth version. This is to be replaced by a versioned library, so it will be pinned to a particular version. There is a crucial fix in this version of ethers that fixes nonce management which is causing issues in the Codex testnet. It also contains a fixes for:
- recreating subscription filters when not found
- `JsonNode.items` symbol not found
- nim-json-rpc to v0.4.4
- nim-json-serialization to v0.2.8
- nim-serde to v1.2.2
- nim-serialization to v0.2.4
- codex-contracts-eth
- currently on branch to support …
> chore: update dependencies, especially nim-ethers to chronos v4 compatible version

- codex/contracts/deployment.nim
PR updates Marketplace contact address for Codex Testnet.
Part of  #983.
> chore: update testnet marketplace address

- Makefile
- flake.lock
- flake.nix
Initialized flake file and added development shell definition.
Referenced issue: https://github.com/codex-storage/nim-codex/issues/940
> nix-flake: Add shell definition

- codex/stores/maintenance.nim
Quick fix `.async` => `.async.`
> fixes incomplete async annotation

- tests/codex/blockexchange/engine/testadvertiser.nim
The advertiser occasionally clears items from the asyncQueue faster than the test will check for them.
> Fixes raceconditions in testadvertiser

- codex/utils/trackedfutures.nim
- removes usage of `then`, simplifying the logic, and allowing `then` to be removed completely
- updates annotations to reflect that all procs (sync and async) raise no exceptions
This PR is part of a larger set of fixes to the codebase that removes usage of a faulty pattern of not awaiting or asyncSpawning futures.
> fix(trackedfutures): removes usage of `then` from tracked futures

- codex/contracts/market.nim
- tests/contracts/testMarket.nim
Closes https://github.com/codex-storage/nim-codex/issues/1028
> refactor: marketplace configuration is cached

- codex/utils/asyncstatemachine.nim
- adds a break in scheduler when CancelledError is caught
- tracks asyncSpawned state.run, so that it can be cancelled during stop
- removes usages of `then`
- ensures that no exceptions are leaked from async procs
- Based on https://github.com/codex-storage/nim-codex/pull/1032
- This PR is part of a larger set of fixes to the codebase that removes usage of a faulty pattern of not awaiting or asyncSpawning futures.
> fix(asyncstatemachine): fixes not awaiting or asyncSpawning futures

- tests/integration/multinodes.nim
After a change in PR #1031, bootstrap node sprs may not work when Hardhat nodes are started with the tests. This fixes it by appending all started client's and provider's SPR to a sequence, and using that sequence of SPRs to start the next node. This means all subsequently started nodes will be connected to its previously started peers.
This also fixes the case when bootstrap SPRs would not be present if no clients were started.
> fix(tests/integration): fix bootstrap node spr

- codex/node.nim
This PR removes the FIXME that is no longer needed.
> chore: remove old fixme

- codex/rest/api.nim
Same as #970 but for download network
> Remove duplicate cors header for download network endpoint

- codex/contracts/marketplace.nim
References: 
https://github.com/codex-storage/codex-contracts-eth/pull/213#issuecomment-2612073331
https://github.com/codex-storage/codex-contracts-eth/pull/211#issuecomment-2612071005
https://github.com/codex-storage/codex-contracts-eth/pull/212#issuecomment-2612069822
> chore(marketplace): update contracts and add custom errors

- tests/integration/codexclient.nim
- tests/integration/codexprocess.nim
- tests/integration/testpurchasing.nim
- tests/integration/testrestapi.nim
> chore: create new httpClient per request

- codex/contracts/market.nim
- codex/contracts/marketplace.nim
- codex/market.nim
- codex/sales/states/filling.nim
- codex/sales/states/slotreserving.nim
- tests/codex/helpers/mockmarket.nim
- tests/codex/sales/states/testfilling.nim
- tests/codex/sales/states/testslotreserving.nim
> chore: add missing custom errors

- .gitmodules
- codex/blockexchange/engine/engine.nim
- codex/blockexchange/network/network.nim
- codex/blockexchange/protobuf/message.nim
- codex/merkletree/codex/coders.nim
This PR upgrades libp2p and constantine packages
> deps: upgrade libp2p & constantine

- codex/node.nim
re-add stream/task monitoring, thanks to @marcinczenko for catching this!
> monitor background tasks on streaming dataset

- codex/contracts/marketplace.nim
- codex/rest/api.nim
- codex/rest/json.nim
- openapi.yaml
- tests/codex/utils/testtimer.nim
- tests/integration/testpurchasing.nim
- tests/integration/testrestapi.nim
- tests/integration/testsales.nim
Reflect the validation rules applied in the contracts side https://github.com/codex-storage/codex-contracts-eth/blob/1982e71d52b6f593cc6c20a3bfad2f70b751d081/contracts/Marketplace.sol#L131-L160
> chore: add request validations

- codex/rest/api.nim
- tests/integration/testrestapivalidation.nim
When testing the new release I noticed that our "required" parameters are not really required...
> fix(api): availability creation validation

- .github/workflows/ci.yml
- Makefile
- codex/codex.nim
- codex/erasure/erasure.nim
- codex/sales/reservations.nim
- tests/codex/stores/testrepostore.nim
This PR bumps Nim to 2.2.4 and fixes the various issues that come with that.
> chore: bump Nim to 2.2.4
